project:
  type: website
  output-dir: docs

website:
  title: "Food Technology, Culture & Ethics"
  page-footer: "Copyright 2022, Shane Crowley" 
  reader-mode: false
  page-navigation: true
  sidebar:
    style: 'floating'
    search: true
    contents:
      - section: "Introduction"
        contents:
          - index.qmd
      - section: "Ontology"
        # contents:
        #   - drafts/definingfood.qmd 
        #   - drafts/fourcauses.qmd
        #   - drafts/isandisnot.qmd
        #   - drafts/replacingfood.qmd
      - section: "Epistemology"
        # contents:
        #   - drafts/knowingfood.qmd
        #   - drafts/waysofknowing.qmd
        #   - drafts/scienceandtechnology.qmd
        #   - drafts/fooddisciplines.qmd
        #   - drafts/toolsforknowing.qmd
      - section: "Semiotics"
        # contents:
        #   - drafts/talkingfood.qmd
        #   - drafts/foodsigns.qmd
        #   - drafts/foodrhetoric.qmd
        #   - drafts/marketingfood.qmd
      - section: "Technoscience"
        # contents:
        #   - drafts/foodstructure.qmd
        #   - drafts/imaginingfood.qmd
        #   - drafts/changingfood.qmd
        #   - drafts/foodprocesses.qmd
      - section: "Appendix"
        contents:
          - drafts/slides.qmd
          # - drafts/reflections.qmd
          # - drafts/interactions.qmd
          # - drafts/syllabus.qmd
      - notes/about.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            url: https://github.com/edibotopic/foodETC
          - text: Report a Bug
            url: https://github.com/edibotopic/foodETC/issues


format:
  html:
    theme: 
      light: [theme.scss]
      dark: [cyborg]
