---
title: Overview 
slide-format: revealjs
css: styles.css
execute:
  echo: false
format:
  html:
    toc: true
  pdf: default
format-links: [pdf]
---

## Introduction

These notes are an *exploration* of topics relating to the design of food products, beverages and nutritional solutions.
They are associated with a module taught to BSc Food Science students at University College Cork, Ireland, which is named **Food Technology, Culture & Ethics** (or *FoodETC* for short).
The course is being developed and taught with the aim of providing a more *systematic* account of food to students that are otherwise focused on scientific studies.
By design, the material does not assume a significant background in science, as most students will have not studied chemistry or physics when taking the course.

This module is spread across _two semesters_.
More detail can be found below.

::: {.callout-tip}
## Where's the rest of the course?
The website will be populated with content as the course progresses.
:::


## Lectures (S1)

In **semester 1**, lectures take place at **4 pm each Wednesday**.

The lectures take place in **CONN-S2** on Western Road.

<iframe title="3D image of S1 classroom" src="https://kuula.co/share/7PLMc?fs=1&amp;vr=0&amp;sd=1&amp;autorotate=0.1&amp;thumbs=1&amp;alpha=0.02&amp;info=1&amp;logo=0" width="100%" height="540"></iframe>

::: {.callout-note}
New notes and slides will be made available before each weekly lecture.
:::

## Lectures (S2)

In **semester 2**, lectures will be at **4 pm each Tuesday**.

The lectures will take place in **FSB-322** in the Food Science Building.

<!-- <iframe title="3D image of S2 classroom" src="https://kuula.co/share/7lRfY?fs=1&amp;vr=0&amp;sd=1&amp;autorotate=0.1&amp;thumbs=1&amp;info=1&amp;logo=0" allowfullscreen="" width="100%" height="540"></iframe> -->

## Notes and Slides

The first set of slides are embedded in the [online version of these notes](https://edibotopic.github.io/foodETC/) — you can interact with them easily on your phone, tablet or computer.
Note that in slide 5/8 clicking (computer) or swiping (phone) will zoom you into specific regions of the slide.

<div>
```{=html}
<iframe class="slide-deck" src="slides/one/"></iframe>
```
</div>

Notes and slides are <u>a framework</u>, which are developed in greater depth during lectures.
To get the most out of the course you need to attend, do the assessments and read assigned material.

:::{.callout-tip}
## Slides

The slides associated with this first lecture can be accessed directly below:

[📽️ Direct link to slides for this lecture](slides/one/)

📃 Pressing <kbd>e</kbd> on a set of slides will convert them into a printable format.

:::

:::{.callout-warning}

Some classes will have no associated slides and will mostly involve
hand-drawn notes and/or class discussion.

It is your responsibility to take appropriate notes (or learn 
how to do so).

:::

The content of the course has the following general themes:

- **Knowing food**: establishing what food is and how we gain knowledge about food
- **Talking food**: investigating how food is perceived/interpreted in society
- **Changing food**: exploring how food is transformed by technology
- **Sustaining food**: confronting the complex ethical and technological hurdles on the path to sustainability
- **Future food**: imagining how future challenges and technologies might shape how food is designed

Individual topics will take 3-4 lectures to complete, depending on class interest and progress.

The course *assumes no prior knowledge of the topics covered*.
It is understood that not all students have studied chemistry, biology or physics.
For this reason, we start with the everyday experience of food (what foods do we prefer? how do we define food? what ways are we convinced to buy food?).
What *is required* — above all — is a willingness to learn new things, engage in the class and think critically.

:::{.callout-warning}
These notes and slides do not provide full coverage of the course content.
`Lectures`, `videos`, `readings`, `discussions`, `drawings` and `assessments` are just as important.
Enrolled students are expected to participate fully in the course and write their own notes.
:::

## List of Assessments

The module involves 100% **Continuous Assessment**:

- Lecture attendance/participation (10 marks)
- Semester 1 class exam (20 marks)
- Semester 2 class exam (20 marks)
- Group presentation (20 marks)
- Critical Essay (30 marks)

Further details on these assessments will be provided during the year.

## Preface to the Module

Food is both astonishingly complex and boringly familiar.
That there is a science of food, and that students study this at a university,
comes as a great surprise to some people.
Yet these same people often have many questions about their own food choices and
how their food is manufactured that are difficult to answer using "common sense".
The effects of diet on health, lifestyle and the environment are some of
the most pressing questions facing society today, and the knowledge
of food scientists will play a key role in answering them.

Some of these questions are age-old – how can we feed a growing population? – 
others more contemporary – do palatable alternatives to
animal-based products exist that are less harmful to the environment? 
— and some quite controversial – should food choice be determined by 
personalised data to prevent diet-related disease?
A university education will not give you the answers to all of these questions, but it
will prepare you to begin finding the answers (or better questions).

I hope you enjoy the module.

::: {.callout-important}

## Vertical Slice

Like most science degrees, each year of the BSc Food Science builds on the foundation of the previous year.
Students might be interested in learning about beer brewing or ice-cream manufacture from day one.
However, to appreciate these topics fully one has to master more foundational material, such as:

- Chemistry (year 1)
- Food engineering (year 2)
- Sensory science (year 3)

Then in year 4 a student is considered ready to approach the full complexity of food product
to the point that they can develop their own in a systematic fashion:

- Product development (year 4)

The difficulty with this approach for students is that for a long while they can feel out-of-touch with what they came to university to study (in this case `food`).
This module is designed as a **vertical slice** through the whole degree.
Samples of each year, ranging from the fundamentals in year 1 to advanced topics in year 4, are found throughout.
The challenge with this approach is that the students have not studied the pre-requisites for the more advanced material.
For this reason, a somewhat philosophical approach is adopted, focusing on general concepts, case studies and critical thinking.

:::

I hope you enjoy the module.
