---
title: Food Structure 
slide-format: revealjs
css: styles.css
execute:
  echo: false
search: false
---

Remember our basic definition of structure:

> A set of elements and their relations

*Food structure* is an important area of food science.
When food scientists refer to "food structure" they often
mean the *microstructure* of food.
**Micro**structure is what is observed under a **micro**scope.
A particle of 1 µm is 1000 times smaller than 1 mm.

<div>
```{=html}
<iframe class="slide-deck" src="../slides/eight/"></iframe>
```
</div>

[📽️ Direct link to slides for this lecture](slides/two/)

Microstructural features are often used to explain
events occurring over short time-scales.
Here are some examples:

**Events**

- Emulsions become unstable due to the flotation of microscopic droplets
- Foams become unstable due to drainage of water through microscopic channels between bubbles
- Gels generate pools of surface water due to the contractions of gellified regions

More generally, food structure can be taken to refer to how different components interact to generate new properties:

**Properties**

- The viscosity of a liquid depends on the interaction of polymers with water
- Liquids transform into gels when the distance between particles is very small

Increasingly, food structure is often studied in relation to human digestion.
This is often referred to as the "food matrix effect", where matrix = structure:

- Casein digests more slowly than whey proteins because it forms a gel in the stomach
- Cooked starch digests more quickly because the sugars are more accessible to digestive enzymes

Often it is not necessary to consider the chemistry or biology of a system when a problem is related to microstructure.

## Foods are dispersed systems

Diagrams and animations can be very helpful when learning about food structures.
However, they are also difficult to reproduce and remember.

A simple shorthand — similar to algebra — has been developed to solve this problem.
Note that it does not do many things we expect from an algebraic equation.
For example, the formulas cannot be solved to yield a number.

Also, it only represents the topological structure of food.
This means that it is primarily based on the notion of **connection**.
For example, this is how we might think of a dispersion of oil and water:

- There are two unique components
- The oil is divided into multiple parts that do not connect
- Every surface point of the oil is connected with water
- Not every surface point of the water is connected with oil
- The oil is therefore discrete and the water continuous

The logic is encoded in the formula $O/W$.

Below you can use a simple app to generate random food structures using this method.
If viewing on a small screen it might be easier to [open in a new window]().

 <div> 
<iframe class="slide-deck" src="https://edibotopic.github.io/disperse/"></iframe>
 </div>

## Dispersions can be unstable

Emulsions consist of one liquid phase dispersed in another, while suspensions consist of a solid dispersed in a liquid.
Play with the animation below to determine the factors that influence the separation.

If viewing on a small screen it might be easier to [open in a new window]().

 <div> 
<iframe class="slide-deck" src="https://edibotopic.github.io/stokes-law/
" loading="lazy"></iframe>
 </div>

## Complex Structures

The structure of different foods is often responsible for their unique properties.
When these foods have to be "replaced" or "mimicked" one of the major challenges is recreating the structure. 
Some examples are briefly described below.

### Milk ($(O+S)/W$)

An emulsion of oil in water and a suspension of casein particles in water. 

### Ice-cream ($(G+O+S)/W$)

A dispersion of gas bubbles, oil droplets and ice crystals in supercooled water.

### Meat ($D_1S@D_1S^3$)

Thre repeating sets of one-dimensional solid fibres, each included in the other.
