---
title: Tools for Knowing 
slide-format: revealjs
css: styles.css
execute:
  echo: false
search: false
---

## Reading and Knowing

Reading text has been the primary method of acquiring knowledge for much of human history.
Scientists learn new ideas by reading journal articles, the public learns about current events in newspapers.
If you want to learn about a new topic you might start with Wikipedia, but to really learn you probably need a good book.
To prepare for my lectures I read from all of these sources and if you have ever watched a good Youtube video they probably have too.

As a student you must read, even when it is hard.
There are two families of problems students face when reading.
The first relates to problems of interest, motivation and enthusiasm.
These are age-old psychological tests that you must learn to overcome.
The second relates to problems of sourcing trustworthy information.
These are new problems that must be navigated in the era of the internet.

Your first instinct might be that anything in print is authorative.
Consider the following sources of information:

- Tweets
- Blogs
- Newspaper reports
- Journal articles
- Press releases from universities
- Books by famous professors

Any of these sources could potentially contain factual and interesting information.
If the source contains a coherant, logical argument it can be evaluated on its merits.
For example, a blog that outlines an effective way to cook a turkey is probably reliable,
if it contains sound advice (cooking the meat through), measurements (target temperatures)
and results (photographs of the results).
Similarly, a Tweet that outlines how to solve a mathematical equation is trustworthy if it
reliably yields the correct result (meaning the logic was valid).
Most people do quite well cooking and calculating with recipes found on the internet.

Newspapers typically have editorial standards that make them more rigorous than a blog, Tweet or TikTok.
For example, if a journalist is making a factual statement they are expected to have a reliable source, such as a witness.
When submitting their article for publication the editors of the journal will check if such standards have been met.
However, these standards are internal to the newspaper and are defined by the culture within that newspaper.
A recipe for cooking turkey in a newspaper is unlikely to be more or less reliable than one found in a blog, because
newspapers have more exacting standards for their News section compared to their Lifestyle section.

Journal articles are considered to meet some particularly high standards and are the gold-standard information source in many disciplines.
A typical process for writing a scientific paper looks something like this (don't worry, you probably will never do this!):

1. Ask a new, interesting question
2. Develop answers through careful experimentation
3. Write up the results and interpret them in a paper
4. Edit and re-draft the article multiple times
5. Submit the paper to a journal where it is screened for quality by an editor
6. Receive reviews of the paper by at least two (anonymous) experts in the discipline
7. Attempt to improve the paper by responding the reviewer comments
8. Hope that the editor and reviewers agree that it is worth publishing
9. Wait to see if researchers in the field refer to the paper in their work

This makes publishing a scientific paper very challenging.
Science has a rigid system of quality control that makes its articles *generally* trustworthy.
However, this does not mean that every paper is correct, perfect or important.
Scientific articles have mistakes, but it is rare compared to other written forms.
The question of how important a scientific paper is can usually not be known until several years later.
If other scientists cite the work, use its methods or adopt its ideas then it has become important.

Frequently students refer to university press releases and popular books in their writing.
You need to recognise that these have not met the same quality criteria as a scientific paper.
They have also been written for different reasons than merely "reporting original findings".
I can write anything I want in a personal blog and nobody can stop me from publishing it.
The reason I would write a blog might be that I want to learn something, I want to reach
a new audience or I maybe I want to do something different than my day-job.

A university press release might serve the function of showcasing a
university and its excellance to the outside world, similar to an advertisement.
Popular books are often not peer-reviewed like scientific papers, and often involve
scientists reaching well outside their specialisation.
Many popular books by scientists are deeply philosophical and contain anecdotes from their personal lives.

All of these sources can be useful, especially when starting to learn a topic.
They can also help us to become enthusiastic about a subject that interests you.
However, they rarely serve as solid foundations for your arguments.

Here are some simple rules when choosing your sources:

- *Popular media*: good for general information and highlighting the cultural importance of an idea
- *Essays and books*: good for well-written summaries of ideas and clear arguments on interesting ideas
- *Blogs and social media*: good for developing interests and being directed to more reliable sources
- *Journal articles*: good for citing factual scientific information, discovering new methods and finding arguments made by scientists and philosophers
- *Literature reviews*: good for a factual overview of a scientific research area and determining the relative importance of scientific findings

## Writing and Knowing

It is a common misconception that if you listen to enough lectures and read enough notes you will understand your college course well enough.
Unfortunately, this is not the case.
Even if not everyone enjoys doing mathematics or physical exercise, it is well understood that practice is required to get better at them.
Similarly, with developing scientific or philosophical understanding it is necessary to practice, and the best practice is often to write.

Most people who write regularly are aware of the following phenomenon:

> I thought I had a good idea.
>
> Then I wrote it down and it seemed stupid.
>
> So I wrote some more and figured out what I wanted to say.

Many people never start writing or give up when they think their writing is stupid.
For this reason, many people go on thinking they have a good idea while never actually having good ideas.
One of the most common traits of creative and successful people is that they write their ideas down and develop them.

The software developer and start-up funder Paul Graham is famous for maintaining a blog where he writes about a range of topics.
Here are some of his thoughts on writing:

> I think it's far more important to write well than most people realize. Writing doesn't just communicate ideas it generates them. If you're bad at writing and don't like to do it, you'll miss out on most of the ideas writing would have generated.

Now consider a selection of advice given by Graham to write well:

::: {.callout}

## How to Write Well --- excerpts from [*Writing, Briefly*](http://www.paulgraham.com/writing44.html)

---

- Write a bad version 1 as fast as you can 
- Rewrite it [version 1] over and over 
- Cut out everything unnecessary 
- Develop a nose for bad writing 
- Imitate writers you like 
- Expect 80% of the ideas in an essay to happen after you start writing it, and 50% of those you start with to be wrong 
- Don't (always) make detailed outlines 
- Mull ideas over for a few days before writing 
- Carry a small notebook or scrap paper with you 
- Write about stuff you like 
- Try to tell the reader something new and useful 
- When you restart, begin by rereading what you have so far 
- When you finish, leave yourself something easy to start with 
- Accumulate notes for topics you plan to cover [...] 
- Go back and tone down harsh remarks 
- Publish stuff online, because an audience makes you write more, and thus generate more ideas 
- Print out drafts instead of just looking at them on the screen 

:::

To increase your confidence with the subjects you are studying in college, the best advice I can give you is to write about them.

## Logic and Knowing

It is common as a student to hear that you are expected to "think critically".
Unfortunately for you, it is rarely explained what critical thinking actually is.
In truth, critical thinking is a broad concept that has varying definitions.
However, there is some broad consensus on important traits of a critical thinker.

Generally, to think critically requires you to be able to assess evidence and arguments.
The ability to assess evidence is --- to a degree --- determined by your level of knowledge about a topic.
During the course of your education at university, your scientific and statistical knowledge will increase and as will your capacity to assess evidence.
The assessment of arguments is something more general and if you cannot assess arguments you might never assess evidence appropriately.

Logic is the field of study devoted to the assessment of arguments.
George Boole, UCC's most famous professor, is primarily known for his work in logic.
People regularly make basic mistakes in logic even when they protest that something is "just common sense".

In logic an argument is simply a set of premisses and a conclusion.
Premisses are put forward in support of a conclusion.
If the premisses are true and the conclusion follows from them then the argument itself is true.

Note: an opinion is sometimes not an argument and usually a bad argument --- we will return to this point later.

### Deduction

The simplest kind of argument to understand is a deductive argument, a famous example being:

1. All people are mortal
2. Shane is a person
3. Shane is mortal

Here, $1$ and $2$ are premisses and $3$ is the conclusion.
In the absence of evidence that suggests an immortal person has existed we must accept $1$ is true.
Similarly, as all available evidence suggests that Shane is a person then $2$ is also true.
Given that is is true that all people are mortal and that Shane is a person then it follows that Shane is mortal.

::: {.callout-note}

The meaning of "it follows" in deduction is usually understood intuitively, meaning something like "the mind is led to believe the conclusion based on the truth of the premisses".

However, if you are the kind of person that wants this explained then there is an underlying axiom that allows us to draw the conclusion above.

The axiom is *transitivity* and can be stated roughly as "If $x$ is $y$ and if $z$ is an $x$ then $z$ is also $y$".

Transitivity is a property of some mathematical operations (if $x$ is greater than $y$ and if $y$ is greater than $z$ then $x$ is greater than $z$).

:::

We can re-write the argument so that it is not **valid**:

1. All people are mortal
2. Shane is a person
3. Shane likes swimming

The conclusion here does not necessarily follow from the premisses.
Usually, this does not mean that the person making the argument is incapable of thinking.
Instead there is usually hidden premisses that if made explicit would render it valid:

1. All people are mortal
2. Shane is a person
3. Shane is mortal
4. All mortals like swimming
5. Shane likes swimming

In the above, the hidden premisses are made explicit, allowing us to more accurately assess the argument.
Now, we have a new problem --- the new argument is not **sound**, which means at least one of the premisses is not true.
In this case, the premise that all mortal beings enjoy swimming is not true or at least highly doubtful.

When you are writing you rarely lay out arguments in numbered form like this.
However, it can be good practice to map out an argument or to check your reasoning.
Frequently, unstated premisses, unsound premisses and invalid arguments result in unclear and ineffective writing.

::: {.callout-warning}

Logic is a huge area. Knowledge of argument structure, validity and soundness is the bare minimum.

There are many other well-known examples of where people can go wrong in their reasoning.

It is not possible to expand on every case here, but you are encouraged to self-study in these areas if you are interested.

:::

### Induction

Induction is another kind of reasoning that is distinct from deduction.
Thinking inductively is thought to be an important feature of science.

While deduction involves a **de**crease in generality from universal (all) to particular (this),
induction involves an **in**crease in generality from particular (this) to universal (all).

A famous historical example is as follows:

1. Each swan observed has been white 
2. All swans are white

Note that this argument resembles the scientific proces of observing the world (1) and interpreting the results (2).
In any scientific study we can only observe a sample of a population and cannot measure everything of interest.
For this reason, we must *go beyond* the available observations to make more general statements.

Interestingly, the above example was later demonstrated to be false.
Black swans are native to other regions of the world that were not familiar to those who made the original statement.

We should then update our argument to the following:

1. Each swan observed has been either white or black
2. All swans are either white or black

Now, some philosophers have argued that this model of induction is problematic, because it is unclear how anyone could ever
reliably go beyond particular facts to make universal statements.

A more representative model for science is something like the following:

1. Each swan observed within our sample was white
2. There is a high probability that all swans are white

It is then understood that scientists are not expressing certainty but rather making a statistical argument from a finite set of data.

### Abduction

The final form of reasoning is probably the least well known but arguably the most consistent with everyday problem-solving.
Abduction involves arguments based on heuristics and approximation.
When people refer to "educated guesses" or "rules-of-thumb" they are typically discussing examples of abduction.

Consider the following:

1. My two friends had a bad fight
2. Today I saw them eating ice-cream together
3. My two friends must have made up

Here we have an observation (1) and another (2).
Based on the second there is a hypothesis (or "educated guess") that the friends made up.
It is possible that this hypothesis is wrong.
For example, they could have agreed to have one last ice-cream before ending their friendship forever.
However, given that people typically do not do that it would seem to be unlikely.
To be a good scientist --- of course --- we should observer our two friends a little more and ask them how they are doing.

The real work of science usually involves **abduction**, when making sense of observations, proposing hypotheses, making further observations and explaining results based on models and heuristics.
However, sometimes scientists use **induction**, especially when they have accumulated a large amount of observations and have a consistent and reliable way of explaining the results.
Scientists also frequently rely on **deduction** as a basic kind of reasoning, for example when thinknig using scientific laws (if heat always travels from warm to cold, then this hot object will dissipate heat to its environment.)

### Opinions

An opinion is usually merely a conclusion with no supporting premisses:

> in my opinion, food should not be processed

When justifying an opinion people often say:

> everyone is entitled to their opinion

So this looks something like:

1. All people are entitled to their opinion
2. I --- a person --- am entitled to my opinion
3. Food processing is bad for health

The (3) here does not follow from (1) and (2) --- by this I mean, we cannot determine whether the argument is true based on the premisses.

Furthermore, if we assume that such arguments are valid then this allows us to affirm the truth of two contradicting statements.
Assume one person argues that the world is round and another that it is flat.
We can use these two "truths" as premisses in another argument:

1. We know that the earth is round
2. We know that the earth is flat
3. The world is round and flat

This is not very helpful if we are in the business of determining what is true and what is false.
While a fact is true, an opinion is merely held to be true by the person saying/writing it.
Opinions are useful for stimulating discussions but not for making good arguments!
The real substance of the above argument is completely trivial:

1. We know that some people believe the earth is round
2. We know that some people believe the earth is flat
3. Some people believe he world is round and others that is flat

By surveying many people in a population we can determine if there is a widely-held position on something.
If 60% of people think food processing is bad then we know what most people hold to be true but not whether it is true.
Such a finding can motivate different actions: for example, a company might decide to reduce their emphasis on processing while another might aim to educate its consumer base on the value of processing.

To briefly conclude, none of the following represent compelling arguments:

- Your opinion, which you are entitled to
- Popular opinion, even when held by a majority
- Actions taken in response to opinions, which can vary

## Doing and Knowing

Lastly, you need some "practical" experience.

Food science --- in my opinion --- is an amalgamation of science, engineering and design.

To be a good scientist you need to become comfortable with planning, performing and reporting experiments.

To be a good engineer you need to develop an understanding of how operations can be combined to transform materials.

To be a good designer you need to develop a capacity to create new concepts and to develop prototypes of your ideas.

