---
title: AI Technology
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---

Sometimes a new technology emerges with a wide range of applications that has the potential to impact the world in a significant way.
You are currently living through an era in which powerful AI-based tools
are being created that generate text, graphics and sound using machine-learning algorithms trained on vast quantities of data that is scraped from the internet.

In the immediate future, such AI technology has the potential to disrupt your college life and your future career, so it is important to explore how it works, its strengths and limitations.

## ChatGPT: Strengths and Weaknesses

In class the recently-published tool ChatGPT was demonstrated.
This tool is clearly useful, insofar as it can (usually) generates coherent responses to whatever prompts you supply.

While it is *possible* to simply ask "generate me an essay/speech" about a given topic, the most productive way of interacting with the tool is to — like the name suggests — engage in a back-and-forth **chat**.
Generally, it will produce a response with *apparent* confidence, even if the text it generates contains vague statements and even factual errors.
The problem for you — as a student at the early stage of your studies — is that it is difficult for you to distinguish between good and bad responses.
Currently, simply trusting that what an AI tool generates is true and correct might lead you to make big errors, even if a significant proportion of the AI output is reasonable and correct.
When finding information "the old fashioned way" this is less of a problem, because you can always try to find *reliable sources*; for example, highly-cited scientific articles, accurate historical records or objective fact-based journalistic reporting.

In my own experience, when asked about topics relating to food science ChatGPT often produces good high-level descriptions of well-established topics.
However, it is not good at providing detail.
Frequently it returns statements containing factual errors.
While it can write citations and references it occasionally seems to make these up!
Although the text generated by these tools may not be flagged by plagiarism software (at least not yet) it could well contain incorrect statements or fake references.
It will also construct responses in obvious ignorance of how the module you are studying is designed; for example, if a lecturer spends an hour discussing a topic in class and you don't pay attend or pay attention then both you and an AI are likely to miss a core point that the lecturer expects you to develop in an assessment.

## Using ChatGPT Effectively

ChatGPT might be particularly useful for generating rough summaries or overviews of a topic that get you through an initial stage of writer's block.
If you are asked to write an essay or create a presentation on a completely unfamiliar topic then ChatGPT might be able to supply you with some general ideas and some references to get you started.
One helpful strategy is to identify ideas in ChatGPT's output that seem underdeveloped or vague and ask specific follow-up questions to try to extract a more clear description — it might be the case that you never get a good response in such cases, which can be a good sign that this might be something you should explore yourself.
This is not unlike the normal practice of doing academic writing, where we write something on a topic, identify which statements we have made that need to be developed further, conduct more research to improve their clarity and/or the evidence to support them, and so on (i.e., "writing is re-writing").

## Problems for you to Consider as a Student

One of the reasons that you are assigned essays, reviews and presentations is to develop your capacity to use writing/reading as a tool to improve your understanding of a topic.
For example, when hired to work as a researcher you might be asked to write a literature review in your first few weeks.
The purpose of this task is not to get marks or to publish the review, but rather to force you to come up-to-speed with research in the area you are going to be doing your research.
An AI could conceivably write this for you and your manager might mistake it for your own work, but you will soon be revealed to know little about the area.

At this stage in your education, several of you might think that doing these projects is all about the **outcome** ("did I pass?", "what grade did I get?") but it is really about the **process** ("did I learn how to do something?").
It is conceivable that two students could do an essay, one student uses an AI and gets 70% and another does not and gets 60%, but the student who gets the lower mark actually learns more, is better prepared for future assignments, understands lectures better and ultimately becomes a stronger performer in the workplace.
In truth, the best approach to take is probably to explore how to use AI as another tool in your arsenal (in addition to plain-old-fashioned writing and reading).
It would be a mistake to ignore such technological developments, as they have the power to make some tasks more easy or efficient; however, as soon as you become simply a *user of AI tools* then you risk becoming replaceable.

## Using AI Tools in this Module

When submitting an essay or presentation in this module you will simply be asked:

> Did you use an AI tool during the completion of this project?

If the answer is "yes" then you will be asked to expand on *how* you used the technology.
For example, you could include images of your prompts and the AI responses.
You could then explain how you probed the AI further after evaluating the initial output from the AI before doing some additional research to explore the topic further.

## AI Prompts and Food Design

One thing that you should consider is how AI technology like ChatGPT — which is based on Large Language Models (LLMs) — could be harnessed in the design of food technology.

For example, could we prompt AI systems to develop rough prototypes of product concepts that could then be explored in the laboratory or kitchen?

This is something that you could begin exploring today: is the tool good or bad at such a task?
How might you use the output it generates to begin the process of product design?

More generally, it might be worthwhile for you to explore the current state of AI technology and AI-based tools, especially in terms of how they might impact the development of technology in food and nutrition.
This is a rapidly-growing area and while you are not being taught specifically about AI in your degree it is something you can investigate in your own time.
