---
title: Defining Food 
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
format:
  html:
    toc: true
  pdf: default
format-links: [pdf]
---

::: {.callout-warning}
## Note

If there are any errors, ambiguities or omissions in these notes please let me know.

You will need to revisit notes during the year as the material is covered. 

Read, take notes and read more (or ask) about anything you don't understand.

:::

Historically, the creation of new knowledge about food has made important contributions to human development.
The harnessing of fire in cooking has even been claimed to be a critical moment in the growth of the human brain (Wrangham, 2009).
Early developments in preservation, such as salting and smoking, alleviated the survival pressure to continuously find new food.
As societies shifted from a context of food scarcity to one of food abundance, there was increased opportunities to focus on other activities, including leisure, creativity and study.
This story is a tale of *progress* but some have argued that current societal problems like obesity are evidence that progress has stalled.

<div>
```{=html}
<iframe class="slide-deck" src="../slides/two/"></iframe>
```
</div>

[Direct link to slides for this lecture](../slides/two/)


## Product Types

Despite the fact that we all eat, there is not always universal agreement on what food *is*, what is *good* food and what might *become* food.
As food scientists are specialists in the study of a food it might be useful to start with what they study.

Professional food scientists work on a variety of product types.
Something like whiskey is not what most people would characterise as "food" due to its limited nutritional value, yet food scientists *do* study whiskey.
Whiskies have other qualities that are valued by people who consume them (e.g., aroma richness, colour intensity, alcohol content).
They must be processed in a very controlled way using operations like distillation to ensure they are safe and consistent.

A bottle of whiskey and a protein supplement are both studied by food scientists while having completely different **functions**.
While the supplement has a greater nutritional value it is itself difficult to characterise as "food" given that it is by definition *supplementary* to a diet consisting of a variety of foods.

If we put aside whether these materials are food and just consider that food scientists are interested in "things that are consumed" we run into the problem of distinguishing foods from drugs.
Indeed, while the food and pharmaceutical industries are distinct there is increasing overlap in some of their products, especially considering the emphasis now placed on biological functions of food products that are beyond basis nutrition.

Few would argue that a calcium tablet is a "food" despite the fact that it contains a nutrient.
Pharmaceuticals are traditionally associated with the treatment, control or prevention of disease.
Yet newer "functional foods" often carry similar promises.

## Our Idea of Food Changes

One of the things that makes food difficult to define is that our idea of what consistutes food tends to evolve.
With the introduction of new technologies — like 3D printing — our concept of food can be is challenged and updated.

Scientists and engineers tend to be `utopian` in their attitude and imagine that all technological development will result in societal progress — they are optimistic about the future.
Others are `dystopian` in their outlook, imagining a future in which technology has damaged society and the planet — they are pessimistic about the future.
Still others have a `romantic` vision of the past, a better time when we were closer to nature — they wish for a future that is more like the past.

All of these worldviews have their blindspots.
New technologies with promise can succeed but they can also fail.
Traditional customs may be demonstrated to be helpful or harmful.
Assuming that everything new is good (neophilia) or that everything natural is good (naturalistic fallacy) are both dangerous.

We must always look for reasons and evidence, while being careful about totalising worldviews.

## What Food Is

### Parts and Wholes

There are two common approaches to beginning a discussion of *what food is*.
In science, there is often a tendency to begin with `parts` (elements, atoms and molecules).
In everyday life we are more likely to begin with `wholes` (appearances, qualities, experiences).
Both approaches are legitimate but they often seem to be in conflict:

> Science seems to tell us to choose foods based on their nutrient levels but should we really be trusting our instincts and traditions?
> 
> — a common view among figures like Michael Pollan, who have [critiqued the food industry in recent years](https://www.youtube.com/watch?v=qaqhKYdhSu8&t=147s)

These approaches are often given names:

- **Holism**: understanding things by studying the them as a whole
- **Reductionism**: understanding things by studying their individual parts

They are commonly assumed to be mutually incompatible (you can take one approach but not the other);
however, when doing science or designing technology it is rarely possible to ignore both approaches.

A "holistic approach" is often incomplete in that it willfully ignores details at a lower level.
A "reductionist approach" is often incomplete in that it willfully ignores details at a higher level.

Both approaches can be effective in specific contexts.
For example, when cooking it is possible to make a decent meal by paying attention to how things look and taste.
On the other hand, designing a meal-replacer that meets label declarations for ingredient levels requires us to carefully quantify parts.

Most **good** food scientists involved in designing products must not only think at both levels but also consider how both levels connect.

Scientists are interested in wholes (or the qualities that wholes are observed to have) but in well-defined ways:

- What causes certain qualities?
- Which qualities do people prefer?
- How can qualities be measured?

While qualities like redness and sweetness are `subjective` this does not mean that scientists are not interested in them.
As the consumption of food is driven to a great extent by subjective factors, food scientists are greatly interested in these properties.

These qualities are only present due to some underlying mechanism.
The quality of redness arises from biochemical processes in ripening.
We would first observe the redness of the food (the whole) and then
determine the underlying cause (the parts).

### Natural and Artificial

There is another way of talking about food that focuses on `ontological categories`.
A significant number of people think it is 'common sense' to opt for **natural** food.
This is assumed to exist in *opposition* to another category called the '**artificial**'.
If we consider concepts like ’naturalness’, ’wholeness’ and ’cleanness’ to be important
then we should understand *what they mean* and *why they are important*.

The question of whether natural and artificial things exist is a deeply philosophical one.
A common definition of the artifical is that it includes anything that is the product of human intervention.
As human intervention has affected most things the usefulness of the category is brought into question.
According to this basic definition, a home-cooked meal is just as artificial as an industrial food product.
Some argue that we should come up with better definitions that tally with the importance we give to these categories in daily life.
For example, we could consider degrees of naturalness in both parts (ingredients) and wholes (meals).

It would take us too long to determine what a good definition might be.
So let's just assume that it exists.
The next question is: can it help us make decisions?
It is often assumed that natural things are good for humans.
Consider, however, mosquitoes and poisonous mushrooms.
All of these are natural while also being clearly harmful.
Consider also some natural processes, like volcanic eruptions and food rotting.
These are also potentially very harmful.

Given the existence of these major counter-examples, caution is required
when making the statement that *all natural foods/medicines* are good.

::: {.callout-tip}

## Be Precise

Many of the things that we value are artificial (furniture, houses, clothing, careers, education, meals).
Most people use words like 'natural' and 'artificial' to describe the world.
It is useful, for example, to look at an unspoiled beach and say it is 'natural' and a skate park and say it is 'artificial', if we are in the business of preserving beaches.
Some problems can arise, however, when the distinction is used as a basis to make judgements about what is good and bad.
This is because both categories are sufficiently broad that they each encompasses good and bad things (This, 2014):

- **Natural and good**: the alcoholic drink known as 'wine' that is generated when grapes are allowed to ferment
- **Natural and bad**: the anion oxalate that forms a variety of salts in plant-based foods and is associated with gout and kidney stones
- **Artificial and good**: synthetic vanillin used in the production of 99% of the world's vanilla-flavoured products
- **Artificial and bad**: *trans* fats produced by the industrial process of hydrogenation that is known to have negative health effects

The assumption that natural things are always good (or bad) is false but so is the assumption that artificial things are always bad (or good).
It is preferable therefore in all such cases to <u>be more precise</u>.
For example, the following statement is helpful to guide our decision-making:

> *trans* fats are bad because of their role in contributing to poor cardiovascular health

However, the next one is overly general and misleading:

> people should avoid all artificial foods because they are bad for your health

:::

### Science Versus Ontology

The process of thinking about parts, wholes and categories *in general* is **not science**.
This does not mean that the process is not important, but it is different.
Instead of doing experiments we try to reason carefully about our ideas.
This can help us decided what is useful or possible to study.

In a specific science what people mean by `parts` is obvious; for example, in physics this might be sub-atomic particles.
When doing ontology we can think of parts more generally, in a way that spans multiple disciplines.
A social scientist does not typically care about sub-atomic particles, as the fundamental parts (individual people) are different in the systems (societies) that they study.
As food science is multi-disciplinary (chemistry, physics, biology, sensory science, etc.) and applied (it is used to design technology) the question *what parts do food scientists study?* is more difficult.

As a preliminary answer: food scientists study whatever parts are relevant to problems involving the preparation, consumption and storage of food.
It is important to remember that these parts are not restricted to nutrients.

::: {.callout-important}
When doing ontology we focus on general ideas.
Redness is visual quality and texture is a tactile quality.
More generally, these are *sensory properties*.
Foods possess many other properties that can be sensed.
Freshness is also a property that is sensed, but its meaning seems less clear (can you think of how it is sensed?).
We could try to identify properties (like freshness) that are ill-defined so we can think about them more clearly.
This would be *doing ontology*, but the clarity it would provide can help us *do science* (how will we measure freshness?).

*Ontology* is a deliberate attempt to probe our assumptions, and help make them *explicit* (Kaplan, 2012: 3).
Once they are explicit we can question them and — if necessary — challenge them so that we can think more clearly.
:::


## Seeking Better Definitions

When asked to define an object as seemingly *everyday* as food many are quick to consult a dictionary.
Here, we will generally find something like:

> a material containing nutrients that when consumed provides an organism with the means to grow

Is this a good definition? Most intuitively answer 'yes'.
However, when asked to describe favourite foods people will mention things like:

- **Sensory attributes** (taste, aroma, flavour, texture, sound)
- **Contextual factors** (sharing food, celebrating with food, food as a reward)
- **Ingredient pairings** (chocolate with caramel, cheese with crackers, beer with chips)
- **Functional properties** (muscle building, weight loss, skin health, life extension)

In most cases, food necessarily contains a significant quantity of nutrients.
However, it is not the case that food **only** contains nutrients.
The primary constituent of most foods is `water`, nearly all foods contain `bacteria` and there is a broad class of other `non-nutritional factors` (e.g., fibres).
Any food scientist that neglects the role of water, bacteria and fibre is not doing their job well!

::: {.callout}

## Water

Food scientists spend a lot of time studying and manipulating water in food systems.
The amount of water in a food is critical in determining the time it takes to rot.
The presence of water in specific forms — like crystals — is also important for the texture of products like ice-cream.
Nutritionally, a significant proportion of our water intake is in the form of food.
:::

Think about ice-cream for a moment.
Why do people buy ice-cream?
Usually because they enjoy certain qualities (coldness, melting, sweetness, texture).
When is ice-cream frequently served?
*After* a meal (not *as* the meal).

Not all food is like ice-cream, in which nutrition is often a secondary consideration.
Some foods — like infant formula — can be considered to serve primarily a nutritional function. However, most foods are selected for a wide variety of reasons (nutrition, sensory, culture, etc.).
Narrowing our definition of food to a single class of molecules (nutrients) or properties (taste) leads to a limited understanding of food and reduces our capacity to design foods for different individuals and contexts.

::: {.callout-note}

## Base Needs?

In primary school most of us encountered the distinction between *needs* and *wants*.
Food is often considered a *need*, like water, rather than a *want* like a VR headset.
As food is needed for survival, this can lead to the view that as long as a food contributes to survival it is good.

Now consider some other "base needs" like clothes and shelter.
Certainly, both jackets and houses protect us from our environments.
However, think about the actual place where you live or the outfit that you are wearing.
Do you think what makes these things "good" is solely determined by their capacity to protect you from the environment?
When you think of how your apartment could be better or what shoes you might prefer are you thinking:

> How will this maximise my capacity to survive in my environment?

The answer is surely 'no' because — living in a safe, rich country — your survival is effectively ensured.
Given that most (though not all) people in a country like Ireland have an adequate supply of nutrients the 
question is rarely 'how will I have enough food to survive?' but rather 'what foods do I most desire?'.

:::

## Nutraloaf

In class we encountered [Nutraloaf](https://www.npr.org/sections/thesalt/2014/01/02/256605441/punishing-inmates-with-the-loaf-persists-in-the-u-s), a meal fed to prisoners as punishment.
From how it is described, the food is claimed to be nutritionally complete.
However, the food is otherwise bland.

Nutraloaf has been the subject of legal cases in the USA that argue it is a Cruel and Unusual punishment.
While many of these lawsuits have been unsuccessful the practice of feeding prisoners "punishment meals" has been outlawed in some US states.
The issue is interesting because Nutraloaf apparently serves the basic function of a food (supplying nutrients), while obviously being a very controversial subject.

Ontologically, this material seems to meet the necessary conditions for being a food but it is also in some sense inadequate.

### Factors to Consider

- A food can only be successful in supplying nutrients if is deemed edible and can be eaten
- The phenomenon of 'taste fatigue' is a recognised problem with meal-replacers and is known to cause nutritional deficiencies in other people in society
- The idea that a single nutritionally complete food can be prepared for all adults is dubious given the complexity of food and individual dietary needs
- Perceived risk is a major factor determining the decision of individuals to consume substances and a lack of trust can negatively affect consumption
- One of the aspects of a diet that is valued by people is our ability to freely choose what should be in our diet

### Questions to Consider

What do you think about nutraloaf?

Would you eat it?

Do you think it's fair that others have to?

How is it different to commercial meal-replacers like Huel or Soylent?

### Enjoyment and Nourishment are Tightly-coupled

Assuming Nutraloaf is nutritionally complete (for argument's sake) many prisoners still do not want to eat it.
Defending nutraloaf on the basis that it provides nutrients does not account for the fact that people need to first desire foods in order to then acquire their nutrients.
For nutraloaf to function as a food it must also be acceptable to prisoners (it evidently is not).

The idea is that the punishment works by depriving the prisoner of enjoyment (sensory blandness) while ensuring they remain healthy (nutritional completeness).
However, enjoying food and being nourished by food are tightly-coupled (we eat the things we want to eat).
We could therefore say:

> A food is nourishing if it has a high nutritional quality and is considered desirable to eat

::: {.callout-tip}
### Bonus Thought: Can Naturalness Be a Useful Guide for Scientists?

While ontological concepts like 'naturalness' are not scientific *per se*
it is still common to hear scientists refer to such concepts, especially when developing technology.

In biomimetics, for example, the focus is on natural structures in the nature that have useful properties.
Scientists can then study them and design nature-inspired materials that benefit from these useful properties.
Given the problem of designing a meat-replacer we can first study the structure of meat so that the structure can be replicated.

This is an example of operationalisation, where an abstract concept is made more concrete so it can be tested.
Here, scientists are not concerned with the philosophical question of whether natural things exist.
They also do not make the universal ontological claim that natural things are better. 
Instead, the category of natural things is assumed to exist, some of those things are studied to determine their properties and attempts are made to recreate those useful properties in artificial systems.
:::

::: {.callout-tip}

## Bonus Thought: Is Anything Natural?

The distinction between natural and artificial is rarely clear-cut.

Consider this example (Bunge, 2003):

seed → seedling → sapling → tree → log → pulp → paper → book

This is a combination of natural and artificial processes.
If the seed was purposefully planted and its environment manipulated to promote its growth, there is a a question as to whether the entire process might be artificial.
:::

## References

Bunge, M. (2003). Emergence and Convergence: Qualitative Novelty and the Unity of Knowledge. Toronto: University of Toronto Press.

Jackson, P., Brembeck H., Everts, J., Fuentes, M., Halkier, B., Hertz, F. D., Meah, A., Viehoff, V., & Wenzl, C. (2018). Reframing Convenience Food. Cham: Palgrave Macmilan.

Kaplan, D.M. (2012). Philosophy of Food. Berkeley: University of California Press.

This, H (2014). Note-by-Note Cooking: The Future of Food. New York: Columbia University Press.

Wrangham, R (2009). Catching Fire: How Cooking Made Us Human. London: Profile Books.
