---
title: Evaporation
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: false
---
---

Concentration refers typically to any operation where water is removed to increase the proportion of solids in a system.
"*Solids*" usually refers to any components that are *not water*.
For example, below is the approximate composition of whole cow milk:

|Component   | Level (%)  | Solid?  |
|---|---|---|
|Water   | 87.3%   | No  |
|Lactose   | 4.8%   | Yes  |
|Fat   | 3.7%   | Yes  |
|Protein   | 3.4%  | Yes  |
|Minerals   | 0.8%  | Yes  |

Milk is 87% water with the remainder being "solids".
Concentrating milk by evaporating water results in an increase in the concentration of all of these solid components.

Thus, concentration involves no fractionation of components in the solids, meaning there is not change in the relative proportion of protein and sugar, for example.
There are several advantages to concentration, including:

- Reduced weight due to water removal
- Decreased microbial growth due to lower water content/activity

In addition, concentration is commonly applied to liquid systems prior to operations like spray-drying, due to the energy efficiency of the concentration operations.

<div>
```{=html}
<iframe class="slide-deck" src="https://edibotopic.github.io/lecture-slides/FS1005_15.html"></iframe>
```
</div>

[📽️ Direct link to slides for this lecture](https://edibotopic.github.io/lecture-slides/FS1005_15.html)

## Evaporation

Evaporation usually refers to a phase change ($liquid \to vapour$) that occurs when the temperature of a liquid is increased above its boiling point ($T_B$).

::: {.callout-note}

Scientists often distinguish between evaporation and boiling as two distinct types of **vapourisation**, where evaporation can occur at temperatures below boiling temperature (think of a water puddle that dries out on a cold Irish day) and involves generation of vapour at the liquid surface, while boiling occurs at or above boiling temperature (water in a kettle) and involves generation of vapour throughout the bulk of the liquid.

I am not convinced that this distinction is critical to understanding evaporation *as an operation*, so I will typically use "evaporation" to refer to the generation of vapour.
You are free to explore the technical distinction further if you wish.

:::

$T_B = 100 °C$ for water in normal atmospheric pressure.
Even at room temperature, some water molecules gain sufficient energy to become vapour but they are very few in number.
As temperature increases, and approaches $T_B$, the number of water molecules entering the vapour phase increases, resulting in a progressively greater *vapour pressure*.
You can imagine the vapour pressure ($T_V$) as being opposed by the atmospheric pressure — as the vapour pressure increases from a small value (at 20 °C) to a big value (at 100 °C), evaporation is able to proceed more rapidly as the vapour more easily overcomes the atmospheric pressure.
When $T_V$ exceeds (or equals) $T_B$ then boiling occurs, resulting in rapid vapourisation.

An evaporator is a machine designed to promote the evaporation of a liquid with dissolved solids (i.e., dissolved substances) so that it becomes more concentrated.
In food processing **evaporation** often refers to an *operation* in which an evaporator is used to concentrate a liquid food or beverage (*via* the mechanism of evaporation).

By *more concentrated* we mean **more concentrated in solids (everything that is not water)**.

::: {.callout-warning}

Technically, both evaporators and driers involve the phase change of evaporation (as does other operations such as distillation).

A way to distinguish them is to remember that an evaporator does not change the form of its input.
So while a spray-drier transforms a liquid into a powder, an evaporator merely changes the properties of a liquid — the liquids become more concentrated

:::

A simple evaporator would consist of an open tank heated to a high temperature (at or approaching boiling temperature).
There are several reasons why this would be a sub-optimal approach, however, due to the high temperatures involved:

1. **Nutrients** may become degraded, as some are sensitive to heat
2. **Energy** costs will likely be high, as generating hot water and steam requires significant energy input
3. **Chemical changes** may occur, as reactions like Maillard Browning are more prominent at high temperatures

For these and other reasons, a specific evaporator design — the *multi-effect falling-film evaporator* — is commonly-used.

::: {.callout-important}

## The Story of How the Evaporator was Invented

If you benefit from human interest stories when learning technical material I would recommend the remarkable tale of how [Norbert Rilliuex](https://www.acs.org/content/acs/en/education/whatischemistry/landmarks/norbertrillieux.html#multiple-effect-evaporator) developed multi-effect evaporator technology.

The principle of operation of modern evaporation technology is largely the same as Rilluex's invention.

:::

## Evaporator Design

The evaporator has several important design features that allow it to work effectively.
The multiple "effects" refer to **stages** where the evaporation will occur.
Each stage consists of an enclosed chamber containing a series of tall, **vertical tubes**.
The liquid to be concentrated falls down the inner walls of these tubes as a film.
In the first stage **steam** is pumped into the shell that surrounds the tubes, heating the film through the walls of the tubes.
A **vacuum** pump is used to reduce pressure in each effect (a partial vacuum is created, removing air molecules that would otherwise oppose vapour pressure), meaning that the boiling temperature of the liquid is reduced.
In the first stage, the concentrate is separated from the vapour, both are then passed into the second stage, which operates at a **lower pressure** than the first — at this lower pressure the vapour can act as the heating medium, promoting the evaporation of more water from the concentrate.
This process can be repeated across up to seven stages, with pressure decreasing at each successive stage as the liquid becomes more concentrated and the vapour is continuously recycled to use as the heating medium (instead of steam).
Vapour is collected at the end of the operation and cooled into liquid water by a **condenser** — this water can then be used to generate steam to initiate the evaporation process again.

To summarise:

### Vacuum

A vacuum is pulled in the evaporator to reduce the boiling point of the liquid.
This means that temperatures as low as 60-70 °C can be used to generate vapour rather than the more severe 100°C.

### Effects

"Effects" refer to stages in the evaporator where the liquid is concentrated, and in each stage there is some vapour removed.
The liquid becomes more concentrated with each stage making it more difficult to evaporate water using hot vapour.
For this reason, the pressure is reduced in each successive stage.
There can be up to seven effects in a commercial evaporator — the more effects that are used the greater the efficiency because more vapour (from the product) can be used as heating medium (instead of steam).
This efficiency is an investment, as more effects increase capital costs.

### Films

Liquid is pumped to the top of the evaporator.
From there, the liquid falls as a film down the inner walls of a long, vertical tube.
The liquid is heated by steam circulating outside of the tube.
As the liquid falls by gravity the vapour generated separates from the liquid.
In most evaporators each stage consists of a large number of these tubes.

### Condenser

Vapour can be turned back into liquid water by a condenser.
This water can then be used (boiled) to generate steam that can be used in the evaporation process.

## Applications and Issues

Evaporators can be used to make liquid, concentrated products like evaporated juices and milk.
As they are highly energy-efficient, they are often used in conjunction with more energy-intensive driers.

During evaporation, the concentration of solids increases, which causes an increase in viscosity.
This may also cause some molecules to be pushed passed their solubility limit.
The combination of high viscosity and reduced solubility can occsionally cause fouling issues (build up of deposits in evaporator tubes).
For example, in whey systems calcium phosphate may begin to precipitate, which is exacerbated by the fact that calcium phosphate is less soluble in warm temperatures.

## Alternatives to Evaporation

There are non-thermal alternatives to evaporation that can remove water.

Many of these are based on membrane filtration; for example, Reverse Osmosis involves the use of membranes that have pores that only allow the permeation of water (allowing the removal of water as solids are concentrated).

The name "Reverse Osmosis" distinguishes it from the phenomenon of Osmosis.
Osmosis occurs when on one side of a membrane there is a high concentration of osmotically-active substances and on the other there is a low concentration.
Common dissolved solids (or "solutes"), like salts, sugars and proteins, are osmotically-active.
For example, when vegetables are added to a salty brine the high concentration of salt results in water moving (via osmosis) from the inside of cell membranes to the brine, resulting in a characteristic "pickling" effect.
In membrane-based concentration the opposite (or reverse) goal is pursued — water must be removed from the solution containing osmotically-active components (salts, sugars, proteins, etc.).
To achieve this pumps and valves are used to increase pressure on the concentrate side, overcoming osmosis.

- Osmosis: water flows from region of low solute concentration to high solute concentration due to natural osmotic pressure differences
- Reverse osmosis: water flows from region of high solute concentration to low solute concentration due to pressures induced by pumps and valves

Reverse Osmosis may be favoured because it can be operated at even lower temperatures than vacuum evaporation (refrigeration to room temperature); however, membrane filtration processes are severely limited by viscosity development when concentration increases.
This means that solid concentrations of 20-25% solids may be possible with reverse osmosis, but this may need to be supplemented with evaporation to achieve higher concentrations (40-60% solids).

## Evaporation = Ultraprocessing?

Some authors have recently suggested that process technologies used in industrial food manufacture result in "ultraprocessed" foods that are nutritionally poor.
The industrial evaporator is an interesting case study in this respect.
Intuitively, the phrase "falling-film, multi-effect evaporator" will be off-putting to someone who is unfamiliar with science and technology.
We cannot simply defend evaporation as making food "more safe" as it is not strictly designed to achieve this goal.

In principle, what industrial evaporation achieves is similar to what is described as a "reduction" in cooking.
To reduce a sauce or soup usually means to simmer or boil a liquid until water evaporates, resulting in some set of positive effects (e.g., increased thickness and flavour intensity).
"Reduction" simply translates to a reduction in volume (due to water loss).
So the first thing to note is that industrial evaporation and kitchen reductions have the same *shared goal*.

Now, **how** the goal is achieved is slightly different.
A kitchen reduction is done in an open pot, heated by a burner, with no vacuum applied.
For this reason, high temperatures of 100°C or greater are required.
This means that a kitchen reduction is very likely to result in the loss or degradation of heat-sensitive components, including nutrients but also flavour compounds (which is usually not measured, of course). 
An industrial evaporator — which *does* apply a vacuum — typically uses less intense heating, meaning there is less heat-induced degradation.
So the two processes — industrial evaporation and kitchen reduction — have the **same goal** (enhance thickness/flavour), are based on the **same principle** (evaporate water and decrease volume) but the industrial evaporator is specifically designed to reduce heat-damage and wasted energy.

The intuition that the "multi-effect falling-film evaporator" must be worse than a kitchen reduction because it less familiar or because we do not see the equipment in our homes must be overcome by developing an understanding of the goal and mechanism of its operation.

## References

Weaver, C. M., Dwyer, J., Fulgoni, V. L., King, J. C., Leveille, G. A., MacDonald, R. S., Ordovas, J., Schnakenberg, D. (2014). Processed foods: contributions to nutrition. *The American Journal of Clinical Nutrition*, 99, 1525–1542, [available online](https://doi.org/10.3945/ajcn.114.089284)

[American Chemical Society (ACS) article on Norbert Rillieux](https://www.acs.org/education/whatischemistry/landmarks/norbertrillieux.html)

