---
title: Protein Story 
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---

The lecture associated with these notes focused on
some historical developments in the scientific understanding of protein.

These notes are a brief summary of the main points covered but you are
directed to the reading and video (accessible through Canvas) for greater
detail.

## Four Elements

People were often interested in the idea that
the world was made of simple parts or "elements".

One of the oldest ideas concerning composition
was that of the *four elements*, which suggested
that the things were composed of varying proportions
of water, earth, wind and fire.

This was closely tied with the idea that consuming
foods with differing quantities of these materials
affected the composition of the body.
Specifically, the four elements were thought to 
correspond to *four humours* in the body, which
were blood, phlegm, black bile and yellow bile.
Ancient thinkers thought that excesses or deficiencies
in these humours were caused by the levels of consumption
of the four elements, and could result in physical or
psychological issues.

Of course, we now know that much of this thinking was
metaphysical rather than scientific.
The Ancient Greeks were wrong about what composed foods
and what composed bodies; however, the general idea that
composition involves multiple parts, and that a healthy
diet consists of a balance of these multiple parts, was
sensible.

## Animal Substance

Early work on food composition that we would now consider
"scientific" was initiated around the time of the Chemical Revolution.
The availability of analytical tools and chemical knowledge improved
the ability of scientists to understand and quantify the parts in a given system.

An early finding was that rotting meat generated ammonia.
It was known at the time that *chemically* ammonia contained nitrogen.
It was also known that nitrogen was abundant in the air.
So there was some confusion as to why and how a substance containing nitrogen was present in meat.

Given that animal meat resembled human muscle, and the general consensus at the time that
meat was highly nourishing, scientists began to wonder if a special "animal substance"
containing nitrogen was responsible for the high nutritional quality of meat.

## Nutritional Technology

While the science of nutrition was emerging minds
quickly turned to applications.

If the "animal substance" was the sole source of
human nutrition, then finding a cheap source of this substance could be a major discovery.

It was known at the time that the viscous broth from boiling bones contained a significant
level of nitrogen (taken to be indicative of the so-called animal substance).

The scientist Magendie hypothesised that a diet of this material (now known to be gelatin)
would be sufficient to support growth and development.

With the support of the French Academy of Sciences he conducted an experiment in which
dogs were fed different diets known to be deficient in nitrogen, including water, sugar, oil,
gum and butter.
All of the dogs became weak and ultimately died.

From this result he concluded that the animal substance was necessary/sufficient for
supporting growth and development;
however, as he had no positive control (a food containing dietary nitrogen) this claim
was speculative.
He simply did not have the evidence and his assumption was based on (false) "common sense"
that dogs could survive on bread alone.
At the urging of the French Academy he repeated the experiment using gelatin.
Much to his disappointment, the results indicated that animals could not survive on gelatin.

If successful, it was hoped that gelatin could be used effectively as a meal-replacement
to feed poor people who could not afford expensive sources of nutrition (like meat).
It should be noted that the historical emphasis on dietary protein was (partially) informed by strange, problematic and illogical ideas.
For example, the success and wealth of some countries was taken to be caused by their high levels of protein consumption; more obviously, the wealth of these countries simply meant they could more easily afford expensive protein-rich foods.

## Beyond a Focus on Single Nutrients 

Over the next several hundred years a greater appreciation of human nutrition was developed.
The so-called "animal substance" was also found in plant-based materials.
Ultimately it was renamed "protein", representing a set of molecules known for their diversity in structure and behaviour.
For example, milk consists of two families of protein: caseins and whey proteins; the caseins are insoluble in acidic conditions while the whey proteins are soluble, which allows their separation.
It was found that proteins were comprised of different proportion of smaller parts (amino acids).
Early figures who considered protein to be "the only nutrient" were shown to be incorrect.
All macronutrients were found to contribute energy in the form of calories.
The development of the calorie concept led to an unfortunate de-emphasis of fruits and vegetables initially,
as these were considered to be of poor nutritional quality due to their low caloric content.
However, this ran counter to the knowledge that diseases like scurvy experiences by sailors could be cured with citrus fruits (which were low in calories).
Scientific knowledge of nutrition, and how nutritional foods can be designed, has increased greatly.
Occasionally, there have been thinkers that have (mistakenly) placed undue emphasis on a specific nutrient (protein) or property (caloric density) when providing dietary recommendations to the general public;
however, most nutritional scientists would now agree that a healthy diet consists of a balance of nutrient sources.
When the actual historical trajectory of the sciences of food are studied, the criticisms levelled at scientists as being "obsessed" with single nutrients rings hollow; indeed, there have been some figures that have made this mistake, but the scientific community has generally identified such errors and developed more nuanced accounts of food and nutrition — this is how a healthy science functions as a community to develop better and more correct ideas, but it can be a slow process.

## Techno-functionality Versus Bio-functionality

Food scientists recognise that industrial products need to be designed for specific use-cases and contexts.
A protein supplement can be useful in the context of attempts to increase athletic performance but it is **not** a meal-replacer.
The chemical complexity of a single citrus fruit or a piece of meat represents a tiny fraction of the complexity of a diverse human diet comprised of multiple foods;
for this reason, efforts to create a genuine "meal-replacer" should recognise the magnitude of the challenge involved.

Gelatin was not successful as a meal-replacer but it became successful as an ingredient for enhancing non-nutritional properties of food.
For example, it can be used to transform a liquid (solution) into a solid (gel), which creates new textural properties.
This is an example of a "techno-functional" as distinct from a "bio-functional" ingredient.
It serves some technical function other than (directly) providing nutrition.

In recent years, many consumers have sought alternatives to gelatin, due to its animal origin.
An important task of food scientist developing a gelled, vegan product — for example — might be finding a protein (or other molecule) from a plant source that serves a similar function.

## References

The nutritional scientist Kenneth Carpenter (1923-2016) wrote a series of historical articles on early historical developments in the science of food that are of interest to both nutritional scientists and food scientists.

They are all available for free online.
In my view, they present a much more balanced perspective on the development and influence of these sciences than can be found in popular works (e.g., Pollan).

[Part 1 can be found here.](https://pubmed.ncbi.nlm.nih.gov/12612130/)
