---
title: Food Disciplines 
slide-format: revealjs
css: styles.css
execute:
  echo: false
---

:::{.callout-note}
## Main Concepts 

- **Safety**: it is a consumer expectation and a legal requirement that the risk associated with processed food is low 
- **Quality**: foods have many qualities - often subjective - that impact their desirability 
- **Diversification**: creating new processes or applying them in a new way can create new markets or solve existing problems 
- **Holism**: food is not just molecules, not just nutrients and not just a commodity, and any overt focus on one aspect will likely lead to market failure 
:::

Soylent is an interesting product.
It claims to be a meal-replacer, which supplies all the nutrients a person needs.
It is marketed at young adults and busy professionals who do not have the time or skills to prepare a meal.
Its story leans heavily on themes and language borrowed from Silicon Valley.

Soylent, however, only succeeds as long as it is processed effectively.
It has a large number of ingredients that need to be mixed together.
Its high protein content creates challenges with viscosity.
To be stable and safe on the shelf it needs to be sterilised, which can cause instability and loss of nutrients.

Soylent starts as a business idea with a potential market. 
It's primary selling point is that it is a convenient nutritional solution.
The multiple ingredients required to produce the drink must be combined effectively.
Ideally, such a product is safe (causing no harm) and efficacious (does what it is supposed to).
The success of such a product can be greatly aided by mutual understanding and collaboration between food scientists, nutritional scientists and food marketeers.

## Your Role

Here's a simplified overview of these inter-related disciplines:

- Food marketers determine what people want and *how a product ought to be* for it to succeed commercially
- Nutritional scientists know *what specific demographics need* in their foods to live healthy lives
- Food scientists *know how to achieve nutritional and commercial goals within a set of practical constraints*

There is a natural tension between these different roles.
Marketers worry that there is a drift away from the needs/desires of their identified market.
Nutritional scientists worry that the healthiness of a product might be compromised to achieve business goals.
Food scientists worry that the goals being set ignore practical limitations on what can be achieved in the factory.

As with most relationships, it is helpful to clearly understand the role that each individual plays in the organisation and how they can best work together to achieve those goals.
In practice, this can be facilitated by sharing some common knowledge.

## Process Knowledge

There is a big problem with the extent to which society understands food processing today.
Too often food processing is assumed to be an unfortunate human invention that causes diabetes and obesity.
It is not uncommon for food marketers and nutritional scientists who work in processed food companies to hold such views.

Perhaps there are some foods that are difficult to defend as being a *net positive* for society but consider the following:

- Nutritional beverages that are fed by tube to patients who cannot eat in hospitals
- Infant formula that is the sole source of nutrition for babies who cannot be breast-fed
- Fortified cereals that have prevented deficiency diseases
- Electrolyte gels that prevent endurance athletes from becoming dehydrated

All of these are specific processed foods that serve a specific function.
When we consider food products in functional terms (what does $x$ product do for $y$ person) we can more easily assess their value.

## Appreciating complexity

The food marketeer can identify a gap in the market for a specific sports nutrition product.
A nutritional scientist can determine what the ideal composition is for that demograpic.
Food scientists can assess whether this is being achieved in the factory and the steps that may be required to fix any problems achieving this goal.

However, this all assumes that nutrition is the sole motivation for processing decisions.
In reality, while we might have a clear nutritional target we also must consider other qualities of the final product.

| Quality   | Quantity    |
|---------- | --------------- |
| Texture   | Viscosity, hardness   |
| Taste     | Level of salt, sugar, acid   |
| Flavour   | Fatty acid profile   |
| Convenience   | Water activity, durability, cost   |
| Freshness | ?   |
| Sustainability | ?   |

All of these factors - in addition to nutrients - are affected by processing.
Effectively processing something often involves careful consideration of how these factors are affected.

Conversations around how to achieve nutritional or commercial goals are made far easier when there is some understanding of the challenges faced during processing.

Some qualities, like freshness and sustainability, are not clearly defined and require collaborative thinking to develop a working model that fits the project context.

# Business

## Financial Context

Food companies need to ensure they have a positive cash flow.
They achieve this by ensuring that their income exceeds their expenses.

A food processing facility consists of a variety of components:

- Raw material intake
- Packaging material intake
- Material handling
- Environmental controls
- Physical infrastructure

As food processing facilities are designed for sanitation and refrigeration the capital investment costs can be expensive.

The processing function of the facility includes:

- Process equipment
- Packaging machines
- Ancillary devices (connections, electrics)
- Process control equipment

Operating costs include raw materials and ingredients, packaging materials, energy, utilities and labor.

## Cost Optimisation

It is estimated that 70% of the costs of goods are associated with raw materials, ingredients and packaging.
Approximately 10% relates to energy, 10% to labor and the remaining 10% to miscellaneous costs.
From this it follows that cost-optimisation strategies should focus on materials.
It is also worth noting that market fluctuations in material costs are a major concern for manufacturers.

:::{.callout-note}
## Effective but expensive ingredients

Cocoa, butter and eggs are all familiar, highly-functional ingredients.

Unfortunately, they are also expensive.
In addition, materials like cocoa are highly volatile, with their price fluctuating with great frequency.

There is an incentive to reduce or eliminate such ingredients in formulations, but this has to be done with great care:

- Customers will expect the product quality to stay the same
- The product will need to be processed using the same equipment
- Nutritional profile and label information may need to change

These projects involve close collaboration between the business, research and operations functions in the company.

**Note**: it is far easier to do a project of this kind with a new rather than an existing product.

:::

Commodities are materials that have their price set by the market.
Butter, grain and milk powder sold by one company is considered as good as that sold by another.
It is difficult to achieve market differentiation for such materials, so producers mostly aim to increase their efficiency and volume of production.

Companies can attain high margins for novel ingredients or products that have not attained commodity status.
For example, cheddar cheese is a commodity and so is the whey powder obtained by drying its liquid byproduct.
Whey protein concentrates, which have been a massive commercial success in recent years, are increasingly viewed as commodities.
Dairy companies are increasingly looking at more and more specialised fractions from whey that can be sold at higher margins.

There are a series of trade-offs here.
Such materials command high costs but can only be produced at small volumes.
The cost of producing the material may be high and require specialised equipment.
A consumer base may not have been developed.
It is key in such cases that the material is produced as efficiently as possible and that — above all — it functions as it is supposed to.

# Nutritional Considerations

It is important to distinguish between different kinds of outputs of a food manufacturing facility.
Helpful categories might include:

1. Products designed for a specific nutritional purpose (infant formula)
2. Ingredients designed to have a nutritional function in a product (vitamin D)
3. Products or ingredients with a general purpose that have a nutritional claim (high-protein yoghurt, gluten-free bread mix)
4. Regular products that legally require a label containing a nutritional label (sliced pan)
5. Products that have not nutritional identity or label (alcoholic drinks)

With respect to nutrition, a food process can have the following potential outcomes:

- Inedible -> edible
- Unfortified -> fortified
