---
title: Food Technology
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---

A technology is something created by people to have a useful purpose.

Usually, a technology is distinguished from other types of artifact
in that it is engineered in some way that incorporates scientific
knowledge.

"Food technology" as a term simply refers to materials and
equipment that is developed with the purpose of creating useful
food products.

<div>
```{=html}
<iframe class="slide-deck" src="../slides/seven/"></iframe>
```
</div>

[📽️ Direct link to slides for this lecture](../slides/seven/)

## Food Scientists Build Things

Not every food scientist is restricted to analysing samples in a laboratory.
Many food scientists are actively involved in the design of food technologies.
The most obvious example of a food technology is a product.

Food products are designed to have specific properties and to achieve certain functions.
Manufacturing processes need to be designed to produce these products.
A given process can achieve a variety of positive effects, including:

- Making an inedible raw material into an edible food
- Extending the period during which a food remains edible
- Improving the sensory and/or nutritional properties of a food
- Creating unique structures or compositions that would not otherwise be possible

::: {.callout-important}

## Safety

The concept of "safety" typically refers to the immediate risk posed by a material.
For example, a food is safe if it does not give you food poisoning.

Toxicologists, however, recognise that some materials can cause harm when consumed over extended periods.
New ingredients, for example, have to undergo extensive testing to ensure that they do not have these harmful effects.

More recently, there has been greater attention paid to dietary issues such as obesity.
The question has been raised: do we pay sufficient attention to how the consumption of specific kinds of processed foods impacts the bodyweight of individuals across their life?

This is an interesting and important question that is very difficult to answer, due to the complex array of factors and long timespans involved.
:::

## Trade-offs

No food process is ideal.
A process will have multiple goals that may be in conflict.

A common example is thermal processing.
In thermal processing, food is heated or cooled,
usually with the intention of improving safety and/or shelf-life.
Many bacteria that are dangerous (pathogenic) can have their levels reduced by heating.
Foods that are sterilised, which effectively eliminates most bacteria, are often exposed 
to temperatures in excess of 100°C for several minutes, rendering them safe to consume.

However, excessive heating can have other effects.
Some nutrients, especially water-soluble vitamins, are sensitive to heat.
Chemical reactions between food molecules can occur, changing the colour, taste and texture.
The scientific approach to food processing involves accounting for these trade-offs.
For example, a scientist may determine what the minimum time-temperature combination is to reduce
bacteria to a target level while minimising negative impacts on vitamins.
If it is discovered that there is always a 25% loss in vitamin C, then the starting material
may be fortified with additional vitamin C to account for this inevitable loss.

::: {.callout-tip}

This strategy of adding an excess of a nutrient to account for process-induced losses is referred to as an "overage".

:::

## Acceptance

Even when a food technology is the subject of much scientific investigation it may still fail.
Take food irradiation, for example.
Irradiation is a non-thermal method of improving the safety and shelf-life of foods.
It has been studied for decades and has been shown to be an effective means of killing bacteria.
Despite this, irradiation technology has not received wide acceptance.
Misplaced concerns that the resultant foods are radioactive or depleted of nutrients have resulted in significant fear concerning the technology.
In fact, when carefully controlled non-thermal treatments of this kind can lead to reduced nutrient losses.
It is also certainly not the case that irradiated foods are radioactive.

::: {.callout-note}

## Herbs and Spices

One of the most common applications of irradiation today is herbs and spices.
In some countries this is the only permitted use for food irradiation.

Herbs and spices are valued for their flavour and aroma, which are characterised by their volatility.

These volatile components can be lost at elevated temperatures.
Irradiation is therefore a "cold" alternative to heat processes for decontamination of herbs and spices that maintains their sensory profile.
:::

In any case, at one point irradiated food was a new technology.
It was subject to considerable scientific research, which determined that it was an effective method of preserving food.
However, to some extent it is a failure, insofar as its level of utilisation is low relative to its potential.

The reason for this is that any technology must not only succeed under the microscope, it must also succeed in the marketplace.
Society needs to be convinced that the technology is not only effective, but also safe and necessary.

## Push & Pull

A common rule-of-thumb is that for all the new food products
that are developed about 8/10 fail.
Therefore, a lot of money and science goes into the development
of products that do not convince people of their value.

Many developments in the food industry are incremental.
For example, consumers may want a breakfast cereal to 
come in a new flavour.
Decreased sales of a gelatin-containing product may prompt 
a company to replace gelatin with a more animal-friendly alternative.
These changes are often "pulled" from the consumer.

A radical new technology may also only result in an
incremental change.
This is the case with a technology like irradiation,
which is a radically different way of processing food
that receives limited application in products like spices.
These new technologies must be "pushed" on consumers,
who may reject them if they are not convinced of their value.

It is not sufficient for a technology to be scientifically-approved to have a large impact in the marketplace.
The technology must be deliberately designed *for people*.
People must be convinced of the value it adds to their lives.

### 3D Food Printing

A technology we have encountered before — 3D Food Printing — is
an interesting case study.
The technology is radical and new, making things possible that were impossible before.
3D printing is not well understood by the public, with the exception of some hobbyists.
3D food printing is even less well understood, with few well-known applications or success stories.
Dozens of scientific papers are published every year on 3D food printing.

The question is: will 3D food printing succeed?
At this point any answer is mere speculation.
However, here is the current state-of-play:

- Scientists are interested in food printing, which allows new structures and textures to be created
- Some particular applications have been suggested, such as the use of food printing to reduce "taste fatigue" in individuals who must consume restricted diets or in the recreation of meat structure in printed plant-based foods
- A small number of chefs and startups have begun experimenting with food printing as a means to create new food experiences
- There is a recognition among scientists of some difficulties with food printing, especially around the consistency with which a wide variety of different food materials can be printed accurately
- A non-negligible number of consumers are concerned that 3D-printed food might be unsafe (for unspecified reasons)

When it comes to a new technology like 3D printing, it is not only a question of doing more science but also of imagining what could be designed for people that would help, interest or excite them.
For any student of food science, there is considerable potential value in developing these new ideas.

## References

To complete...
