---
title: Four Causes (draft)
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
format:
  html:
    toc: true
  pdf: default
format-links: [pdf]
---

:::{.callout-warning}
The notes and slides below are in a `draft` state and may be changed.
:::

In food science we are interested in *how to describe food*.
We want to develop *models* for understanding the different kinds of food we might encounter.
Food is diverse and today there is an abundance of scientific information about food, making it difficult for people (including students) to know where to start.

In this lecture we will discuss a simple *ontological* model from ancient times that is useful for framing our thinking about food research and design.
The model comes from *Aristotle*, a natural philosopher and polymath from ancient Greece.

<div>
```{=html}
<iframe class="slide-deck" src="../slides/three/"></iframe>
```
</div>

[Direct link to slides for this lecture](../slides/three/)

## The Four Causes

Aristotle existed at a time when thinkers first began to imagine that the world was constructed from simple building blocks (atoms).
To Aristotle, this was a *reductive* explanation that neglected other aspects that were required to explain the world.
In his writings he considered everyday objects like statues and asked:

> How can we fully describe what makes this thing called a "statue" a statue?

He suggested that such questions are usually answered with an appeal to four causes.
We can think of these as four (be)causes, *this object is what it is **because** of these four aspects*.
The four causes were: **the material cause**, **the formal cause**, **the efficient cause** and **the final cause**.
To simplify this terminology we will use the following scheme:

- *Matter*: referring to the material cause
- *Form*: referring to the formal cause
- *Process*: referring to the efficient cause
- *Function*: referring to the functional cause

When thinking about any food product *in general* our description of it should account for these four causes (at a minimum) if we want to give a *complete explanation*.


### Matter

The things scientists study consist of physical **matter**.
These things are distinct from immaterial things like spirits and fairies.
A material thing has physical properties, like mass, density, hardness and size.
The matter that comprises a table could be wood. The matter in a salad could be vegetables and dressing. The matter in a probiotic supplement would be specific bacteria and some material that acts as a carrier.
When we are talking about matter it is important to consider the **scale** we are interested in.
In everyday life we are interested in the macro-scale, things that are usually larger than a millimeter and that can be seen by the human eye.
In science we often look at the matter that constitutes the parts of these visible objects, which are invisible but measurable using special equipment like microscopes, which allow us to see objects like microorganisms and oil droplets that can be about a thousand times smaller than a one millimetre (micrometers).

### Form

The form of something is often associated with how it is perceived.
It is closely associated with the concept of *qualities*.
For example, an apple might be shiny, red, sweet and round.
All of these are perceivable qualities of that apple.
More generally, the apple has a certain capacity to reflect light when exposed to a light source, a certain colour when visually observed, a certain intensity of sweetness on the tongue and a certain geometrical shape, among other qualities.
While these qualities can be measured they are often perceived **subjectively**, with individual people (or subjects) sometimes interpreting them differently.
If we cut a cross-section of the apple we can study its **structure**, which can also be considered an aspect of its form.
For example, the pulp, seeds, stem and skin of the apple all exist in a specific spatial relation to each other (the apples are embed in the pulp, the skin surrounds the pulp, the stem emerges at the top).
Form is perhaps the broadest of Aristotle's concepts and is often suggested to be the *essence* of a thing (what makes it what it is).
For example, a table can be made from plastic, steel or wood as long is has a structure that allows you to place objects on its elevated, flat surface.
This is known as *multiple realisability*, which here means that tables can be made of multiple different materials but need to have the same underlying structure in order to work. 

::: {.content-visible when-format="html"}
::: {.callout-note}

## Meat Structure as Repeating Fibres (click-through animation)

To progress through the animation **click** on the image or **swipe left**.

<iframe width="100%" height="280px" src="../slides/three/sozi/meat.sozi.html"></iframe>

[Click here for full-screen version of animation of meat structure](../slides/three/sozi/meat.sozi.html)
:::
:::

::: {.content-visible when-format="pdf"}
::: {.callout-note}

## Meat Structure as Repeating Fibres (click-through animation)

[Click here for a link to a simple animation (opens in browser)](../slides/six/sozi/meat.sozi.html)
:::
:::

### Process

A pile of wood is not a table, but becomes a table when arranged or assembled into the form of a table.
This arrangement of matter into a form is a **process**, which can be natural or artificial.
The growth of the wood in the tree was a natural process, while the construction of the table by a carpenter was an artificial process.
In other words, natural processes emerge spontaneously without human intervention, while artificial processes always involved some degree of human intervention.
As humans, we make things that would otherwise not be found in nature: houses, furniture, books, containers, vehicles, clothes, weapons, tools and — of course — food.
Many things that we consider "food" would not be food without **human intervention**.
For example, many grains and nuts cannot be consumed without having their hard shells removed.
Animals cannot be eaten directly, as the meat must be separated from the hide, bones and organs.
Soy milk is not found in nature, but must be extracted from soybeans by dilution, blending and extraction.
In other cases, foods do not remain food for long enough to be a reliable source of nutrition unless they are preserved, with practices like salting and smoking being performed for centuries for this reason.
Each product we make involves an underlying process, and the process often shapes the character of the final product.
A process is simply a series of ordered steps that generate an output from a given input.
Every food, whether made in a kitchen or made in a factory, involves a process.
For example, rotting and fermentation are both natural processes involving microorganisms, although only one has a desirable outcome.
Even then, in a case like brewing, the fermentation process is carefully controlled to achieve the desired effect.

### Function

A function is the end which an object is supposed to serve.
Tables are expected to support solid things without them sliding off and breaking on the floor.
A glass is expected to hold water unless tilted at an angle such that it can be drank.
Each of these simple objects has a well-understood function in human life and they are designed with this function in mind.
Food in general can be thought of as having nutrition as a/the primary function.
However, it is difficult to ignore that many people consume certain foods for different purposes.
Consider ice-cream — for example — which is typically consumed primarily for pleasure.
If we design an ice-cream but ignore this fact then we are unlikely to produce a *good* ice-cream.
This is one way of defining what a *good food* is: a food that fulfils a well-defined function.
A food can also be multi-functional.
For example, a protein bar is design to be 1. convenient and 2. nutritional.
When evaluating whether a protein bar "works" we would need to evaluate it on at least these two criteria.
It is not sufficient for a beverage that must be consumed through a tube-feeding apparatus in a hospital to have the right nutrients, as the liquid must also *function* such that it can flow reliably through that tube.

:::{.callout-note}
## Functional food

In recent years the term "functional food" has become popular among food scientists.

As all food has a function the term seems confusing at first, but typically it is taken to mean:

> A food that has a function that goes beyond the conventional functionality of a food product

In this area there are special ingredients that can impact specific aspects of how food and body interact, like how eating a probiotic food can influence the gut microbiome or how some fatty acids are linked with brain development. 

Some foods may even function to stop us eating (too much), such as those made with satiety-increasing peptides that make people who struggle to limit their food consumption feel more "full". 
:::

## The Structure of Food Science

Arguably, modern food science is structured loosely around the four causes mentioned above.

There are projects focusing on:

- *Matter*: what is the composition of a food? This kind of work is common in Quality Control roles.
Scientific papers of this type are published in journals like [Food Chemistry](https://www.journals.elsevier.com/food-chemistry)
- *Form*: what qualities and structure does a food have, such as how its molecules are arranged microscopically.
This work is important in Research & Development roles. Scientific papers of this kind are published in
journals like [Food Structure](https://www.sciencedirect.com/journal/food-structure).
- *Process*: what ways can we manufacture food effectively? This kind of work is common in Food Production roles.
Scientific papers of this kind are published in journals like [Journal of Food Engineering](https://www.sciencedirect.com/journal/journal-of-food-engineering).
- *Function*: what functions do foods have technologically or biologically. This kind of work is common in a wide
range or roles, and usually requires collaboration with nutritional scientists when biological functions are
being tested. Scientific papers of this kind are published in journals like [Food & Function](https://www.rsc.org/journals-books-databases/about-journals/food-function/).

In food products these different areas intersect in complex ways.
Consider a vitamin D-enriched nutrition beverage:

|Function              |Matter                               |Form                       |Process                           |
|----------------------|-------------------------------------|---------------------------|----------------------------------|
|Delivery of vitamin   |Oil carrier, vitamin and water       |Structure of an emulsion   |Homogenisation to stabilise oil   |

To design a functioning product we need knowledge of what the product will do (its function), what ingredients we need (the matter),
what structure and qualities the ingredients generate (the form) and what operations will be necessary to produce it (the process).

::: {.callout-note}

## The Four Causes in Design Thinking

While it is not common to encounter the four causes in science (could be considered: *the sciences of the natural*) it is more common to encounter it in design (*the science of the artificial*).

Simon (1969), Jones & Gregor (2007), and Rauterberg & Feijs (2015) all invoke Aristotle's ancient theory of the four causes when explaining the practice of design and how it "works".

Design can be considered the creation of an object or system to fulfill specific criteria.
Typically this requires the designer to *imagine* possibilities (what the creation might become).
This *possibility space* is constrained by a variety of factors that focus the effort (time, cost, physics).

Food products are designed systems.

:::

## Applying the Four Causes

When asked the questions:

- What is candy floss?
- What is a protein supplement?
- What is drinking milk?

It is not sufficient to answer:

- A sugary snack
- A thing used to build muscle
- A white liquid

In each case we are simply describing food according to a single (be)cause.
Aristotle would ask us to consider each of the four factors that cause these materials to be be what they are.

For example, consider the second case:

- Matter: predominately protein
- Form: usually a free-flowing powder
- Process: protein enrichment, heating and spray-drying
- Function: convenient source of protein for muscle-building

We now have a more full description of this material.
Each aspect could be described in more detail, depending on your knowledge of the product and the context in which you are working.

::: {.callout-tip}

## Food Architecture?

In his recent book *Future Foods*, Prof. Julian McClements — a well-known food scientist — draws a comparison between the work of food technologists and the work of architects (extracts are from page 30 of the 2019 edition):

> The creation of foods in home, restaurant, and research kitchens has many similarities to the design and fabrication of buildings.
> [...] food architects must choose the most appropriate building materials and assembly procedures to construct the final product

It is worth noting that when an architect designs a bridge they are not merely thinking of how much cement and iron is needed (`material`).
They must also consider the cost and time required for building (`process`).
The most famous architects are also highly imaginative, designining structures with interesting shapes, patterns and textures (`form`).
People using and viewing these creations, they might come to be considered beautiful and may even become cultural icons (`function`).

> [...] mass-produced homes and foods allowed many people to experience a level of luxury and convenience they had not been able afford before. What they lacked in novelty and refinement, they made up for in greater social inclusiveness.
> The challenge in the future is to create mass-produced houses and foods that also speak to our souls.

Many architects are comfortable with the idea that the aesthetics of a building are important, but this type of thinking makes many food technologists uncomfortable ("We are scientists, not artists!").
The comparison made by McClements might suggest that we should consider our role a little differently and consider the variety of ways in which food can be meanginful to people in their daily lives.

There is a strong tradition in architecture of developing theories of how architects should approach their work.
A famous example is the principle that **form follows function**, which suggests that how something looks (form) should reflect what it is supposed to do (function).
Could similar principles be followed in food design?
:::

## Background

Aristotle is one of the most famous ancient philosophers and is considered the most influential *natural philosopher*, which was the precursor to the modern concept of the scientist.

He is known for the writing influential books on most topics you can imagine, including physics, politics, biology, psychology and astronomy.

One of the general problems that interested Aristotle was:

> how can we provide good explanations?

He grew frustrated at the explanations that were being provided around him.
When asked "What is a statue?" someone might say it was a lump of stone or marble (matter), another that it was a person-shaped object (form) and another that it was the product of sculpting (process).

Aristotle suggested that an *exhaustive* account of a statue would have to include at least these three aspects. He also thought that the object's function or *telos* (Greek for "end" or "function") is also essential to any description.

Some statues were crafted to pay homage to a great citizen, others in praise of a God and others to ridicule a defeated enemy. These different functions would have to be considered when evaluating whether a given statue was a good one.

Aristotle was skeptical of theories like atomism that were emerging in his time, which suggested that reality could be described by reference to fundamental part(icle)s.
He did not think that such theories were sufficient to describe simple everyday objects like tables and statues.
As an alternative method of explanation he developed the **Four Causes**, which he outlined in detail in lectures that were recorded by his students and compiled into a book called *Metaphysics*.

> *meta* directly translates as *after* and here referred to the fact that Aristotle's lectures on these topics came literally *after* those he delivered on *Physics*. In modern usage metaphysics (and the related field of ontology) has come to mean the study of physical concepts that are beyond the scope of physics. The philosopher of science [Karl Popper](https://plato.stanford.edu/entries/popper/) considered that the ancient atomists who proposed the existence of atoms were doing metaphysics because they could not investigate atoms in a way that we would now consider scientific. While metaphysical questions ("Is the world made of atoms?", "What causes must be considered to describe an object?") may be impossible to study scientifically at one point they may later stimulate scientific research, at which point people cease to refer to them as metaphysical questions and consider them science (as was the case with atoms).


## Science of the Artificial

Broadly speaking, in the history of Western civilisation there have been two approaches to understanding the world:

- **Rationalism**: the use of mental reasoning to discover truths about the world
- **Empiricism**: the use of sense experience to understand truths about the world

Aristotle's teacher Plato is thought of as a rationalist.
Plato's *Theory of Forms* suggested that there were ideal forms, such as the circle, which we only experienced imperfect representations of in daily life.
For Plato, studies like mathematics (which relied on mental reasoning rather than physical observation) allowed us to glimpse these ideal forms.
Aristotle was more grounded and in several ways resembled what we understand today as a scientist.
For example, Aristotle did extensive studies on animals and plants that are collected in his biological works.

::: {.callout-note}

Being *empirical* does not necessarily mean being *scientific*.
Empiricism places a value on sense experience of reality (what can be observed through sight, smell, sound, etc.).

While scientific studies are often sparked by these experiences, scientists typically design experiments to develop an understanding of their **causes**, which may not be observable (at least not without sophisticated equipment).

In general, scientists value sense experience as a guide but also understand that it can and does mislead us.
:::

By placing a value on what can be studied through direct observation, Aristotle was more *empirical* than someone like Plato.
Another important thing to realise about Aristotle is that many of the examples he cites are *artificial* objects.
Up until the 19th century works like those of Aristotle were referred to as "natural philosophy".
Modern "natural science", with its specialised disciplines, rigorous conventions and emphasis on experiments largely displaced natural philosophy.
The presence of "natural" in natural philosophy and natural science reflects that they are both generally concerned with understanding the nature of physical reality rather than human concerns, such as art and politics.
However, even when doing natural philosophy, Aristotle used many examples from crafts and technology (things that people made for a purpose).
Some of the models Aristotle developed have an obvious and uncontroversial application to objects like tables and cars but are more problematic when applied to science *per se*.
Keep in mind then that the *Four Causes* is being treated here as a model for understanding **technology (artificial systems)** rather than a philosophy of science.

---

:::{.callout-warning}
Aristotle was a great thinker and continues to influence scientists, philosophers and mathematicians today. However, there have always been those that disagree with his ideas and we must be careful not to extend them to areas where they do not work well.

In ancient times the main opponents to Aristotle's views were the *atomists* who consider atoms (matter) to be sufficient to explain all things. Many centuries later, Francis Bacon — considered to be the founder of the modern scientific method — rejected the formal and final (function) causes and urged scientists to focus on material cause (e.g., atoms, molecules) and efficient cause (e.g., heat, motion).

A significant rejection of Aristotle's ideas occurred in biology with the theory of evolution. Aristotle would suggest that an animal had a specific *telos* (purposeful function) that governed its growth and development; however, evolutionary biology maintains that animals develop through random genetic mutations and natural selection.

Models like the four causes are not "scientific theories" as we normally understand them.
They are *heuristics* or rules-of-thumb that guide us in our thinking, especially with regards to technology.

Versions of the four causes are most commonly found among **designers** who are in the business of creating clothes, buildings, software, furniture, lessons and any other thing you can imagine that people use or consume. Of course, food scientists in their own way are designers also, because they make/design things for people. Many of the examples Aristotle gave in his original works were of things people made (statues, tables) rather than natural things (animals, plants).

When using the four causes as a heuristic, it is important to keep in mind that it is most appropriate when guiding how we approach questions concerning technology (making things for people) rather than science (understanding nature).
:::

## References

Aristotle (350 BCE/2016). *Metaphysics*. C. D. C. Reeve (translator). Indianapolis/Cambridge: Hackett.

Jones, D. & Gregor, S. (2007). The anatomy of design theory. *Journal of the Association for Information Systems*, 8(5).

McClements, D. J. (2015). *Future Foods: How Modern Science is Transforming the Way We Eat*. Cham, Switzerland: Springer.

Rauterberg & Feijs (2015). The Significance of Aristotle's Four Causes in Design Research. *Design Issues*, 38(4).

Simon, H. A. (1969/1996). *The Sciences of the Artificial* (3rd ed.). Cambridge: MIT Press.
