---
title: Good Food
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---
---

::: {.callout-warning}

These notes are in a draft state and may be subject to
some minor changes in the future.

:::

The point was made early in this module that science and technology are two
different activities. In its purest form, the goal of science is to develop a
more clear understanding of the world. A scientist can study a problem in
chemistry — for example — without necessarily thinking about why it might be
important "in the real world". Technology concerns the creation of materials
that are useful or that provide some *good* to the world. Making technology is
therefore always **normative**, as it reflects some idea of *making the world
better*.

The scientists and philosopher made some important remarks about the ethics of
technology. One of his main observations was that technologists seem to claim
credit for the societal goods provided by technology while rejecting any blame
for any harms that are caused by technology. For example, when defending food
processing many scientists point to the success of technologies like
pasteurisation. However, other technologies like hydrogenation have been found
to be potentially harmful. To be consistent we must accept that a technology
can help but also harm. An awareness of both possibilities makes it more likely
that we can work on technologies that are helpful.

::: {.callout-note}

## Ethics of Social Media and Food Manufacture

Consider social media platforms like Instagram and Facebook. It has been shown
that compulsive use of these platforms is associated with mental health issues
in some groups. This has led to calls for the creators to be "more ethical" in
the design of these technologies. These companies now often hire ethics
advisors to help steer how they design their products.

If we expect the designers of software to be guided by some ethical principles
why would we not expect the same of those who design our food? Is it reasonable
to suggest that there are ethical problems affecting software development but
not food manufacture?

:::

<div>
```{=html}
<iframe class="slide-deck" src="https://edibotopic.github.io/lecture-slides/FS1005_16.html"></iframe>
```
</div>

[📽️ Direct link to slides for this lecture](https://edibotopic.github.io/lecture-slides/FS1005_16.html)

## Ethical Issues Are Many and Varied

When we think of ethical issues it is often tempting to think of obvious
examples. For example, most of us would agree that animals should not be
tortured before being slaughtered. Most people agree on this issue and there
are laws and regulations in place to stop such practices. Some, however, argue
that no animals should be slaughtered for meat because it inflicts needless
harm. Others suggest that we must reduce our consumption of animal products to
prevent environmental issues that will harm other people. These issues are
**contested**, in that there is not universal agreement on the course of action
we should take as a society. These kinds of contested issues often arise when
problems are complex, meaning they have multiple interacting components. For
example, in this case we might consider:

- The nutritional needs of people
- The rights and dignity of animals
- Cultural traditions around meat-eating
- Economic motivations to maintain meat production
- Environmental problems due to meat production

Someone might be convinced that there are environmental issues associated with
meat production, while finding it difficult to change dietary habits that they
have developed since childhood. Another person might agree that killing animals
is morally wrong but find it difficult to identify adequate nutritional
replacements. A government might wish to encourage companies to develop more
sustainable alternatives to meat but be afraid of job losses that might occur
if the meat industry is negatively affected.

## Less Obvious Ethical Issues in Food

The case of meat production is therefore more complex than preventing the
torture of animals. It involves a complex set of questions relating to (at
least) the nutritional needs of people, cultural norms around diet, the welfare
of animals and the environmental effects of our manufacturing technologies. By
looking more closely at some of these cases we can begin to find where food
scientists can have a role in these developments.

::: {.callout-important}

## Turning an Ethical Problem into a Practical Problem

Discussions about the ethics of the problems that we face as a society are
important and enriching. However, it can sometimes be important to transform an
ethical problem into a practical one that can be solved in a tangible way.

A really good example of this is the question of speeding. There is a moral
argument as to why people should not speed in their cars: it increases the risk
of causing harm to people. However, it is unfortunately the case that many
people are not convinced by this argument, especially when short-term
motivations (enjoying speed, getting somewhere on time) override the ethical
concerns.

How can this be transformed into a practical problem? **Speed bumps**. When
confronted with a speed bump the driver must think "If I go too fast I may
damage my car on this speed bump".

When thinking about ethical issues in food, it can be fruitful to identify
convincing ethical arguments (we need to reduce our reliance on animal
products) and then transform them into practical problems (we need to make this
vegan cheese melt properly).

:::

### Milk Alternatives: Not All Created Equal

The answer to such problems are rarely "easy". Take a similar question, which
relates to milk alternatives. It is recognised that there are problems
associated with water use and methane emissions in dairy production. This has
led many to assume that milk alternatives are "more sustainable".
Representatives from the dairy industry, who have a vested interest in the
outcome of this debate, suggest that they are inferior.

Rather than "taking sides" here, we need to consider the facts. There is a
problem with the environment that is partly due to methane emissions. There is
an existing issue with water scarcity, which will be made worse by climate
change. Given that dairying is associated with both high levels of water use
and methane emissions it is worthwhile considering methods to either solve
these problems or exploring possible alternatives.

In the case of alternatives they are not all created equal. For example, almond
milk can be considered to be sub-optimal in some respects. It is associated
with high levels of water use and it has a poor nutritional profile.

If you are motivated by ethical concerns for finding environmentally-friendly
and nutritionally-healthy alternatives to animal-based products then you might
need to look beyond your immediate instinct that "plant-based is better".
Instead, you might weigh up what specifically cow's milk offers to society in
its current form and what issues it presents. Looking at the alternatives,
which ones are more likely to offer an alternative that is good for the
environment, nutritionally strong but also palatable to those who are familiar
with the taste of cow milk?

### Cheese Alternatives: Not Good Enough (Yet?)

To successfully replace something it is often not sufficient to convince
someone of the ethics. For example, it could be argued that a vegan cheese
product is a more ethical choice than Cheddar cheese, from the perspective of
environmental sustainability and animal welfare. However, as it stands, many
vegan cheese products suffer from major sensory issues (i.e., they do not taste
very good). This is a major impediment to their widespread uptake in society.

Food scientists must therefore consider what functionality a traditional cheese
product has. Most vegan cheese on the market today contain significant levels
of starch and coconut oil. For this reason, they tend to have much lower
protein levels than traditional cheese products. Some cheeses like Mozzarella
also have a melting behaviour that is expected for specific meals (e.g.,
pizza). Vegan cheeses containing starch and coconut oil do not melt like
Mozzarella, meaning that they are inadequate replacements in this particular
case. Food scientists must therefore consider how to alter the composition of
vegan cheese so as to improve their nutritional properties as well as their
melting behaviour.


### Personalised Nutrition: A Question of Autonomy?

Future technologies, which are yet to be developed or are under active
development, may present new ethical issues. Consider personalised nutrition, a
general set of technologies that aims to design our nutritional intake based on
data gathered from smart devices and genetic testing. It
could be argued that this deprives of us of our autonomy as individuals, in
that it limits our capacity to make choices about what we want to eat. There is
also a question of how these data might be used against us; for example, if
companies have access to data that suggests we have not been "disciplined" enough
in our diet might this impact our ability to access insurance and healthcare?

These and many other questions of this kind are beginning to be asked and we
need to be aware of them so that we can engage with them intelligently, rather
than assuming the technology is simply _good_ or _bad_.

### Ultraprocessed Foods: Ethics follows Evidence?

A few years ago [an
executive](https://www.nytimes.com/2013/03/17/opinion/sunday/how-to-force-ethics-on-the-food-industry.html)
from a large food company quit his job and argued that ethics needed to be
"forced" on the industry. In this way he acted as a
[whistle-blower](https://www.citizensinformation.ie/en/employment/enforcement-and-redress/protection-for-whistleblowers/).
This executive felt strongly that the manner in which the company manufactured
foods was harmful to society. He called for the food industry to be required to
take a more ethical approach to food production. Similar views are now shared
by those who advocate for a decreased emphasis on "ultra-processed" foods in
the diet. Some argue that the *more ethical* stance is to manufacture more
"minimally-processed" foods.

However, the categories that are used to distinguish these broad classes of
food are _vague_. They are based on notions such as something being
"_recognisable_ as _whole_ food", which is highly subjective. These critics
also often fail to consider the *context* in which foods are consumed. For
example, infant formula, Irish whiskey and a meal-replacer might all be defined
as "ultra-processed". Such definitions typically hinge on whether the process
has many steps and/or ingredients.

It might be difficult to justify whiskey consumption by appeals to enjoyment
and tradition, given the social and medical consequences of alcohol
consumption. However, a meal-replacer — which necessarily requires multiple
ingredients and processing steps — is often the only feasible nutrient source
for a sick individual.

If foods and beverages that are used in very different contexts and for very
different reasons are grouped together then it can lead to strange conclusions.
Imagine we invented a category called "super dangerous activities" and I included
in this category walking, shopping and deep-sea diving.
After looking at the number of total deaths and injuries for this category I find
an alarmingly high number.
I conclude that people need to reduce the amount of walking and shopping that they
do.
Clearly the things I have grouped together in this category do not make sense.
The danger associated with deep-sea diving is inflating the danger of
the category as a whole and thereby the dangerousness of the other activities.
With categories like "ultra-processed" there are similar issues.
While there is evidence to support that excessive consumption of high-sugar,
high-fat and high-alcohol foods is associated with various health issues,
there is no evidence that has established a link between the
number of processing steps and negative health impacts.
Including a product in this category because of its number of processing
steps in effect makes it _guilty by association_ (like walking and shopping).

Many authors who have written about food processing are not food scientists or
engineers. For this reason, there are major gaps in their reasoning. They will
argue that a processing step that includes "falling-film vacuum evaporation" is
less healthy than a home-cooking step like boiling. In reality these two steps
are virtually identical in terms of their scientific basis and their actual
effect. The primary difference is that the industrial evaporator is designed to
minimise both energy usage and the impact of heating on the nutritional
properties of the food.

## Ethical Frameworks

::: {.callout}
This is a very brief overview of this area and is designed to get you started thinking about them.

Readings are provided on Canvas for those of you who wish to read further.
:::

For centuries, philosophers have debated how we should approach ethical
problems. The field of ethics is vast and intricate — it is not possible for us
to cover it in detail. However, we will try to introduce the topic so that we
are better prepared to explore it in our own time.

Consider the (in)famous [trolley
problem](https://en.wikipedia.org/wiki/Trolley_problem). Remember: this thought
experiment is not designed to teach you how to react when there is an immediate
threat to life. Its purpose is to help us reveal inconsistencies in our
thinking so that we can identify potential gaps in our ethical reasoning.

An interesting fact is that most people would pull a lever to kill one person
instead of five but [many would refuse to push a person to their death to save
five lives](https://en.wikipedia.org/wiki/Trolley_problem#The_Fat_Man). In the
first case people often appeal to a moral principle that is known as
utilitarianism, which basically states that we should aim to minimise harm (in
this case by sacrificing the one for the many). However, their reaction to the
second case violates this principle (they let the one live and the many die).
When prompted to explain their reasoning in the second case people struggle and
appeal to the vague idea of "not playing a direct role" when pulling a lever.
The use of a technology (the lever) seems to absolve them of their sense of
responsibility.
The interesting thing about such thought experiments is not that they help us
to make critical life-or-death decisions but rather that they reveal some
inconsistency in our thinking.
If you think you are a utilitarian but go against utilitarianism in one of
your answers then perhaps there is more nuance required when justifying such
decisions.

::: {.callout-important}

## Utilitarianism

An ethical framework in which the ethical act is always the one that improves
the well-being of the majority, even if some harm is cause to the minority.

The word "utility" generally means the *good* or *pleasure*, so utilitarians
argue for "maximising utility".

Some issues associated with this framework include questions over who (or what)
is considered in the moral calculation — for example: should non-human beings
and/or future generations be considered? In addition, there are concerns that
utilitarian thinking can be used to justify mistreatment of individuals or
small groups if it benefits a majority, which many find objectionable.
Utilitarians have offered more nuanced versions of this framework in attempts
to rectify some of these problems.

:::

What can be learned from this inconsistency? Well, we seem to absolve ourselves
of moral responsibility when our actions and their consequences are
**mediated** (when there is some spatial or temporal distance between our
actions and the effect of our actions). We might feel responsible for not causing
food poisoning when making dinner for our friends, but may (wrongly) feel less
responsible when designing a manufacturing process that provides food that
could harm many more people — it is critical that we avoid this instinct, if we
wish to have a positive impact on the world.

In the context of business, an ethical framework that is commonly proposed is
the idea of self-interest (egoism). For example, we might be worried that a
local baker could try to make more profits by replacing a portion of their
flour with cheaper sawdust. The argument is that it is useless to tell this
baker to stop this activity for ethical reasons; instead, the baker should
consider that if people find out, perhaps due to a perceived loss of quality in
his/her goods, then it will affect his/her business negatively. For this reason, the
baker maintains high-standards purely due to his/her interest in ensuring the
survival of his/her business. It is unclear how such reasoning plays out in the
modern context of industrial manufacture, where people are less familiar with
how products are made and less likely to detect issues with their production,
especially if the consequences are long-term in nature.
In this sense there is a significant difference between food poisoning (immediate)
and obesity (long term health effect).

::: {.callout-important}

## Egoism

Like utilitarianism, egoism is a *consequentialist* theory, in that it is
justifies its moral arguments on the basis of consequences (usually for
people). While utilitiarism is immediately concerned with consequences for the
majority, egoism is only concerned with consequences for the individual.
Egoists argue that if everyone seeks to maximise the good for themselves (their
own "self-interest") that this will (indirectly) lead to better outcomes for
society.

An example from Adam Smith — a famous Scottish economist writing in the 1700s –
relates to food producers like bakers, butchers and brewers. Smith suggested
that a baker might have unethical instincts, such as mixing their flour with
sawdust in order to reduce costs and increase profits. However, what can
prevent such unethical actions is the baker recognising that in the event that
this behaviour was discovered (they are observed or a customer gets sick) then
his business (self-interest) would suffer. Smith was writing at a time when a
lot of food was purchased from small producers, where — arguably — most
consumers were closer to the production of food than they are today. Given that
most people do not see what happens in modern food factories and health
problems associated with diet are not necessarily immediate, egoism as a
guiding ethical principle does not seem fit for purpose. Indeed, the existence
of laws and regulations governing the production of food suggest that external
controls are often necessary to prevent bad actors seeking to take shortcuts
for profit.

:::

A more explicit ethical framework, which aims to maximise benefits and minimise
harm for the greatest number of people is called utilitarianism. Like egoism,
it focuses on the consequences of our actions. Utilitarians, however, consider
the consequences for other people and not merely themselves. One issue relating
to utilitarianism is challenge in deciding who is considered in the
calculation, which things count as harms and which things count as benefits.
For example, when some food manufacturing practices are criticised (convenience
food, for example) food scientists often argue that it is good that people are
given a large choice of options. Here, the critics and the scientists seem to
place a different weighting on specific benefits when doing their calculation,
with the scientists perhaps emphasising choice and the critics emphasising
health in all cases. In discussions around sustainability, the beings we are
potentially harming are often somewhat abstract, which presents another
challenge to utilitarian thinking; for example, people today may need to make
personal sacrifices (foregoing benefits to themselves) in an effort to improve
the situation for future generations. 

::: {.callout-tip}

## Deontology

From the Greek *deon* meaning duty, deontology suggests that we should not
directly consider consequences when evaluating ethical decisions. Duty-based
ethics often appeal to principles or rules that we should *always* follow in
*all* circumstances (universal laws). The famous thinker associated with this
line of thinking is the German philosopher Immanuel Kant. Kant is famous for
his "categorical imperative", which he proposed in different forms. For
example, he argued that we should always act so as to treat other people as
ends in themselves rather than mere means. In other words, people should be
treated with dignity and not just as instruments to improve our own lives. He
also argued that when we decide to behave in a specific manner we should at the
same time be able to will that everyone else would act in the same way. In
other words, if you are about to do something but think in general that it
would be bad for others to do the same thing then you should not do it.

When creating technologies we should be cautious about thinking of consumers as
mere profit-generating devices. When making a decision to modify a product in
some way we should ask whether we can do this while being comfortable with the
idea that others would do the same.

:::

Some ethical frameworks do not directly consider consequences at all, but
rather a respect for duties and rights. This type of ethics is called
deontology, and its theoretical underpinnings can be quite difficult to work
through in a short amount of time. For now, consider the famous oath taken by
young doctors entering the profession, which establishes their ethical duties
as involving four principles:

1. Beneficence: you should actively seek to improve welfare
2. Non-maleficence: you should actively seek to avoid inflicting harm
3. Autonomy: you should respect the patient's right to choose a treatment in an informed manner
4. Justice: you should aim to provide and distribute help in a fair way

These *duties* that apply in all circumstances. Few of us would argue that we
would like doctors to throwaway their ethical code when they are responsible
for our treatment. It is useful to keep this code in mind when considering
ethical issues around food production — should a similar code be adopted?

- There is a distinction between improving welfare and avoiding
harm; for example, it is not sufficient to merely ensure that a product does
not kill or poison, it should also actively improve the lives of those who use
it. 
- People should be able to make a free, informed choice between a product and
its alternatives, preferably in an informed way.
It is not sufficient to persuade someone to buy something by making them
confused or anxious.
- Whatever products that are produced should not only benefit the most
privileged in society, but should be distributed fairly, especially to those who need
them most.
It is undesirable to have a product with excellent health benefits that only the rich
can benefit from.
