---
title: Parts and Wholes
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: false
---

## Ontology

We are seeking **general** ideas about food rather than particular ones.
If we started listing all of the particularities of different foods, such as redness, freshness, spiciness
then we would have a very long list.
We would throw our hands up at some point and say 'it's complicated'.

::: {.callout-tip}

## Objects and Relations

As an abstract study, ontology can be applied to many different cases:

- A family is a set of people (objects) with an ancestry and/or affinity (relations)
- A meal consists of a combination of ingredients (objects) that are edible to people (relation)
- A sentence consists of characters (objects) that can be combined according to syntax rules (relation)
- A mathematical formula consists of symbols like numbers (objects) and operators like addition (relations)
- A diet consists of quantities of specific foods (objects) that satisfy some dietary goals (relations)

The definitions above have been *stipulated* by me and you might disagree.
For example, you might think that a better account of a meal would include:

- Additional objects (cutlery, plates, courses, drinks, dinner guests, the price)
- Additional relations (order of courses, food-drink pairings, comfort with setting, familiarity between people)

When doing ontology it is possible (in theory) to reach for a full account of a system.
Often in science we must draw a boundary somewhere to make the problem tractable.
:::

Ontology is similar to mathematics in that it involves the abstract study of objects.
When doing ontology, however, we usually try to determine what we can say about reality.
For most mathematicians, talking about sets or numbers does not mean that these objects exist physically.
Mathematics is neutral with respect to reality and is only concerned with mathematical objects.

At a very basic level ontology concerns two kinds of thing:

1. Objects
2. Relations

From these simple types of things we can reason about a lot, including structures and systems.
The question *what is an emulsion?* is answered by considering the objects (oil and water) and the relations (the oil is dispersed in the water).
An emulsion is a structure that is defined as a dispersion of oil and water.
This structure has important properties — it can dissolve both water-soluble and fat-soluble vitamins, for example.

::: {.callout-important}

## Taxonomies and Food Pyramids

A *taxonomy* that you encounter in biology is a kind of ontological model.
Typically, a [taxonomy](https://www.britannica.com/science/taxonomy) classifies objects into a hierarchy.
This means between any two objects there is an order ($x$ is either higher or lower than $y$).
In a biological taxonomy the highest level (or 'rank') is the most general while the lowest is the least general.
Plants and animals share general attributes of Life, but a red fox and a white rose have different attributes as different Species.

The traditional [food pyramid](https://www.safefood.net/healthy-eating/guidelines/food-pyramid) is an ontology of this kind — but objects at the lowest level (fruits, veg) are considered more foundational to the diet.
A less common type of model is a *meronomy*, which classifies objects on the basis of parthood.
[MyPlate](https://www.myplate.gov/), a replacement for the food pyramid, consists of a meal (the whole) and its parts (fruits, grains, veg, protein, dairy).
This model attempts to establish what the necessary components should be for every meal.
Revisions to the food pyramid have taken place multiple times over the decades.
There continues to be debate over this issue because people disagree over what factors are important when categorising food.
For example, increasingly there are calls to include environmental impact in such classifications.
:::

A structure is simply a set of objects and the relations that hold between them.
Meals have a structure because some courses (main) follow other courses (starter).
A university class has a structure because some person (lecturer) teaches other people (students).
Systems are structures that are dynamic — the parts and structure may change over time.
For simplicity, we often think of systems as fixed but most are in flux.
Market demand for a product may change based on a variety of socioeconomic factors (trends, wars, pandemics).
The composition of milk in Ireland changes in composition as a function of the season and climate.

Any system can be described in terms of parts and wholes:

- A classroom is a whole consisting of a teacher and students
- A kitchen mixer is a whole consisting of a motor, shaft and paddle
- A salad is a whole consisting of (typically) cold ingredients and dressing

::: {.callout}
If I brought a kitchen mixer into the classroom to do a demonstration then the mixer would be a **sub-system** in the classroom.
Two friends who begin to ignore the lecture and start their own conversation also form a sub-system, and so on.
Much of reality can be analysed into sub-systems and many systems — in this way — can be considered super-systems (comprised of multiple sub-systems).

:::

When describing the `structure` of a system we are interested in the *relations* between the parts.
A relation is just some way that two or more parts form a connection (physically or conceptually).
For example, a teacher and a student can be described according to the following relation (in block capitals):

> teacher TEACHES student

A motor and shaft in a mixer:

> motor DRIVES shaft

A salad as:

> dressing COATS ingredients

An egg is:

> liquid INSIDE shell

It is always possible to develop a new *model* for our system.
Consider the classroom example, which assumes one-way communication between teacher and student.
Below we have a more complex model, describing a case in which `student A` attends class and is taught by the `teacher`.
The communication is bidirectional, because the student asks and answers questions.
`Student B` did not attend class, so relies on what the other student tells them about the class.

```{dot}
digraph G {
  layout=neato
  teacher -> "student A"
  "student A" -> teacher
  "student A" -> "student B"
}
```

::: {.callout}

## Models

Models are representations of reality used to frame a set of problems so that they can be studied effectively.

A model may be revised as new evidence emerges.

:::

It is common for thinkers to consider two ways of approaching the study of such systems:

- **Holism**: things should be understood by studying the thing as a whole
- **Reductionism** (or 'individualism'): things should be understood by studying their individual parts

Reductionism is commonly associated with scientific thinking, which — we will see — is somewhat of a simplification.
The reason for this is that good scientific explanations do not only consider parts, but also how parts relate with each other and the whole in question (through interactions, mechanisms and so on).
In this way science is *systematic*.

::: {.callout}

## Systemism

An approach to studying the world that considers the mechanisms by which parts interact as wholes within a given environment.

The object of study is always a system, which can be defined in terms of composition (the parts) and structure (the whole).

Note that the environment (or context) is critical: ingredients behave differently in different media; foods are tolerated more or less well by different individuals; diets can be more or less successful for different lifestyles.
:::

Advocates of holism commonly consider that important properties of wholes *emerge* in a manner that is not explainable by reference to their parts.
This often leads to assumptions that certain properties are — in effect — mysterious and unexplainable.
As a result, holism is often an unscientific position, as it asserts that there are real, important things that cannot be investigated or understood.

A food scientist is interested in the qualities that wholes have (is this food product enjoyable?) as well as the mechanisms by which parts determine these qualities (what molecules are associated with this enjoyment?).
Food scientists therefore operate at and between two levels:

- **Macro:** the qualities that can be experienced and observed
- **Micro:** the parts and interactions that culminate in qualities

Moving from macro to micro is `analysis` (studying the molecular cause of observed food decay).
Moving from macro to micro is `synthesis` (building a model of food decay based on observation and analysis).
In science, we constantly move between analysis and synthesis.

```{dot}
digraph G {
  micro -> macro
  macro -> micro
}
```

This concept will be covered in more detail in the `Epistemology` lectures.

::: {.callout-note}

## Emergence

Emergence is an ontological concept that suggests that a set of parts when combined can produce a whole with properties not possessed by any of the parts.

For example, a $H_2O$ molecule does not have the property of *viscosity* (resistance to flowing) but when millions of these molecules are combined into a liquid that liquid is observed to have viscosity.

Similarly, one person does not have the property of *social cohesion*, but citizens in a country do have social cohesion when operating as a group of people.

Emergence is sometimes argued to make reductionism (and science) insufficient to explain reality; however, scientists do not deny emergence and do not attempt to explain emergent properties solely by reference to parts.

Scientists and holists agree that certain qualities seem to "emerge".
The difference is that in science it is assumed that there is an explanation (it may just not have been discovered yet) while in holism it is often assumed that no such explanation can be found.

:::

### Boundaries and Levels

To make progress we often need to draw a *boundary* around the (sub)system that interests us.
When working on anything we usually operate within some constraints (e.g., time, money).
We may draw a boundary around the macronutrients of food, proteins (P), sugars (S) and lipids (L).
In symbols this could be written:

$$Food = \{P,S,L\}$$

This, however, is quite limited, as food also contains micronutrients, like vitamins (V) and minerals (M):

$$Food = \{[P,C,L],[V,M]\}$$

Food also contains taste (T), flavour (F) and aroma (A) molecules:

$$Food = \{[P,C,L],[V,M],[T,F,A]\}$$

::: {.callout-tip}

## The Meaning of these Symbols

These type of equations might be familiar to you from *set theory*, which everyone studies in school.

Food can be defined as a set of elements (elements meaning *elements of a set* rather than *chemical element*).

Thinking strictly in nutritional terms:

$$Food = \{[P,C,L],[V,M]\}$$

This means there are two subsets (inside the square brackets) — micronutrients ($Mi$) for the first subset and macronutrients ($Ma$) for the second.
We can then define the nutritional composition of food ($F_n$) as the union of these subsets:

$$F_n = Mi \cup Ma$$

Now assume that we have similar definitions for the structural elements of food ($Fs$), the psychological elements of food ($Fp$), the economic elements of food ($Fe$) and so on (...), we can then define food ($F$) as:

$$F = \{Fn,Fs,Fp,Fe,...\}$$

**You do not have to learn these equations and will not be examined on your ability to understand them.
They allow complex ideas to be expressed in a single line and are useful tools to order our thinking.
When thinking through these concepts you might benefit from tis approach.**

:::

When trying to solve a food science problem we can restrict ourselves to *chemistry* but — as discussed in class — we can include different aspects of food in our analysis when thinking in terms of *physics* and *biology*.
For example, in class I mentioned how we can consider *bread* in terms of its chemical composition (what is its gluten content?), its physical properties (how elastic is it?) but also the biological mechanisms that give it structure (which yeast content will generate the optimal fermentation?).

For a moment, let's think bigger, and imagine a food product in a supermarket:

- The food has a chemical composition
- The food has an appearance, perceived by the shopper
- The food has a format and package, influencing how it can be used
- The food has a price, which the shopper must be willing to pay
- The food has competitors that may be more or less preferred
- The food might have a health claim and this could be true or false
- The food has been manufactured and transported, giving it an environmental footprint

Consider a case where a consumer sees a product in a shop and considers buying it.
The product has been manufactured in an environmentally-friendly way and is rich in a variety of nutrients.
However, they recently spoke to their friend who heard a news story about that product causing a case of food poisoning.
The consumer does not buy the product because of the perceived risk, even if it meets other criteria (e.g., nutritional quality, environmental sustainability).

```{dot}
digraph G {
  food -> "shopper A" 
  "shopper B" -> "shopper A"
  "shopper A" -> "shopper B"
  "news story" -> "shopper B"
  "safety risk" -> "news story"
  food -> "safety risk"
}
```

To fully understand food *as a system*, and as a sub-system interacting with other sub-systems, we often need to consider multiple factors.
As our time and resources are limited we sometimes need to draw a boundary around a smaller set of things in order to — basically — *get work done*.
However, when we do this we must not forget that a boundary has been drawn (the map is not the territory).

::: {.callout-important}

## Levels of Analysis: The Map is Not the Territory

If food scientists are confronted with a problem that involves particles that sink in a beverage to form a sediment, they may restrict their analysis to:

- **Whole:** suspension of solid particles in liquid
- **Parts:** solid particles, surrounding liquid

They can then develop a physical solution to the problem: making the particles smaller so that they sink more slowly.

In this case there is no advantage to studying the system at a finer scale (molecules) or a larger scale (supermarket).
However, the nature of this analysis does not mean that the scientist denies the existence of molecules or supermarkets!
:::

There is a sense in which food is a collection of chemicals, a sense in which it is a physical system, a sense in which it is an economic commodity, and a sense in which it is a source of nutrients for human growth, and a sense in which it is an object of desire.
All of these ways of categorising food can be useful.
Because we are in a university classroom we have the luxury of *thinking big* so that we can develop a complex understanding of food.
[The mathematician Eugenia Cheng in a talk at Google gives an excellent example of `thinking in systematic terms` about the phenomenon of gaining weight.](https://youtu.be/YHZKX0H6cUE?t=1196)

::: {.callout-note}

## Reductionism Involves Small Boundaries, Not Small Components

Reductionism is often associated with thinking in terms of physically small things (atoms, molecules, gears).
For example, when it comes to environmental issues it might be suggested that it is reductionist to talk about molecules and we should instead focus on the environment.
Molecules are small, the environment is big and the environment contains molecules.
The assumption is then that if we focus on studying the bigger thing then we will understand the system fully.

However, a strict focus on molecules and a strict focus on the environment **both** "reduce" our thinking to a particular level of analysis.
By drawing a boundary around observable things in the environment we restrict ourselves to a surface-level understanding of the problem.
By drawing a boundary around microscopic things we lose sight of how they make important contributions to the environment.

Waste from a factory can pollute a river which can be observed to decrease the population of fish.
However, it is often the high level of phosphorus in these wastes that causes eutrophication, promoting the growth of algae and — in turn — depleting oxygen that the fish need to survive. 

Understanding the underlying (micro-level) events helps us identify the cause of the (macro-level) problem and develop strategies to prevent its occurrence (not every waste is phosphorus-rich).
There is a benefit to integrating the two levels of analysis.

:::

## More on Boundaries

In recent times, food scientists have needed to expand the boundaries of the systems they study, especially in the context of sustainability.
Previously, a food manufacturer may have simply considered how their raw materials can be converted into products and the profits that can be made from their sale.
Today, the manufacturer may need to consider the conditions for the workers that produce the raw materials, the environmental impact of their factory and the health impact of their products.
In this way, the ontology of the food scientist has expanded, and they now consider a broader range of objects, relations and structures in their work.

::: {.callout-warning}

It is always wise to question our ontological models.
Since ancient times thinkers have constructed taxonomies that suggest men are "higher beings" than women.
These false ontological models can have negative practical consequences (e.g., the right to vote).

While less immediately controversial, the designers of MyPlate's decision to distinguish "protein" as a type of food
(it is normally considered as a nutrient) from other types (conventional types like fruit) should attract
our attention:

> what is "protein" supposed to represent as a food group?

Other more recently-developed types of food — like convenience food — have escaped easy definitions.
Convenience food is often considered to be unhealthy but Jackson et al. (2018: 223) give the example of meal kits, which are convenient for people who want to minimise time spent shopping or planning for their meal while having contents that would *not* normally be called "convenience foods". 

:::

