---
title: Science & Tech 
slide-format: revealjs
css: styles.css
execute:
  echo: false
---

Science and technology are closely linked activities but they are not the same thing.
When working on food projects you might sometimes be focused on one or the other.

Below we consider some basic differences between the two and then how both are related.
We then look at each in more detail.

::: {.callout-tip}

## Smart-phones

What made Apple's i-phone one of the most successful technologies in the 21st century?
Touchscreen smart-phones already existed when Steve Jobs first announced the device.
Consider the following:

- The minimal design was aesthetically pleasing
- Steve Jobs gave a very persuasive pitch
- Apple made best use of the latest technology
- Technology had advanced due to the latest science

In truth, it was probably a combination of these and other factors.
The lesson is that if we are involved in designing products we cannot approach the problem narrowly.

:::

## Science

In school we sometimes learn about the Scientific Method, an ordered list of steps that describes the scientific process.
The reality is that science is a more complex set of activites.
below is a list of some of the features of science:

- Science is an activity with a goal of creating knowledge about the world
- A scientific question is usually one that is testable
- Many scientific questions are also falsifiable
- Communities of scientists maintain quality standards
- When a scientific study is submitted for publication it is reviewed by experts
- Scientists build on previous work, whether they agree or disagree with that previous work
- Pure science has not direct concern with producing anything other than new knowledge

## Technology

Technology is always *designed* to have a certain function (or set of functions).
The technology must then succeed in the marketplace, i.e., people must want it and buy it.

- Making a technology usually requires a working knowledge of the system (not just a craft)
- Technology always serves a purpose, which is to fulfill one or more functions in society
- For a technology to be a "good" technology it must function effectively
- For a technology to be successful it must function and be desired by people
- People do not desire technologies for strictly functional reasons
- New technologies raise ethical questions (should we use this or will this cause harm?)
- New technologies raise aesthetic questions (how should this be presented to people?)
- New technologies influence culture (did convenience food help women enter the workplace?)

## Science and Technology

- The development of a new technology often benefits from scientific knowledge
- Technological developments often generate new scientific questions
- Both require creativity (asking new questions, devising new tests)
- Both require discipline (repeatability, communication) 
- Both involve a competition of ideas, science among the scientific community and technology in the marketplace 
