---
title: Science & Food
slide-format: revealjs
css: ../styles.css
execute:
  echo: false
search: true
---

::: {.callout-note}

These notes are a recapitulation of some of the ideas in the recent section, and discusses some topics that could not be covered during class time.

:::

Food science is an innately *techno-scientific* discipline.
Much of its scientific work is focused on the design or improvement of technology.
Ideally, this technology provides some benefit to society, which supports science and technology through funding.
This virtuous feedback loop is depicted in the animation below.

**Hover over `society` and click on the `up arrow`:**

<iframe width="500" height="500" frameborder="0" src="https://ncase.me/loopy/v1.1/?embed=1&data=[[[3,636,518,0,%22Scientific%2520knowledge%22,0],[4,644,316,1,%22Society%22,1],[5,646,119,0,%22Food%2520Technology%22,3],[6,863,319,0,%22Food%2520Design%22,5],[8,425,319,0,%22Food%2520Science%22,4]],[[5,8,-51,1,0],[8,3,-36,1,0],[6,5,-66,1,0],[4,8,-13,1,0],[3,6,-54,1,0],[5,4,46,1,0],[3,4,39,1,0]],[[432,468,%22Generates%22],[862,486,%22Applied%2520in%22],[874,179,%22Creates%22],[436,173,%22Studied%2520by%22],[609,226,%22Benefits%22],[540,363,%22Funds%22],[685,434,%22Benefits%22]],8%5D"></iframe>

## General Features of Scientific Knowledge

Philosophers continue to argue over what makes science *special* as a form of human knowledge.
There is general agreement that the following features can be recognised in the scientific process.

- **Falsifiable**: a scientific claim can — in principle — be tested and determined to be false
- **Mechanistic**: scientific facts are justified by reference to testable causal mechanisms
- **Explanatory**: science does not merely observe effects, it explains what causes those effects
- **Generalisable**: scientific ideas can be applied successfully in a range of problems
- **Objective**: scientific studies are designed to eliminate or minimise the influence of personal bias
- **Inter-subjective**: a scientific work is evaluated (subjectively) by a community of peers who form an (inter-subjective) consensus on its merits 

A scientific claim might be wrong but even then it is typically wrong *for the right reasons*.
This means that the scientists believed in their claim and had a justification, but it turned out to be false.
Subsequently, people can determine how they were wrong in their justification and develop better justifications that get closer to the truth.
Contrast this with a mere *opinion*, where someone has no justification for their belief but happens to guess right.
This person might feel good about being right but they were lucky and cannot explain how they arrived at that conclusion.
Furthermore, repeat the scenario 100 times — how often are they likely to be right using this approach?
Providing justifications for our beliefs is important, especially when discussing important and potentially dangerous topics like food and diet.

::: {.callout-tip}

## The Scientific Paper

I have [a blog](https://edibotopic.com/blog/) and I have a PhD; however, what I publish on my blog is not as reliable a source of information compared to a scientific paper.
Universities and newspapers sometimes summarise the findings of a scientific paper, but these summaries are not as reliable as the original scientific paper.

On my blog, I choose when to publish the material and nobody checks or edits what I write.
Universities and newspapers want to emphasise why the paper is important; in the first case,
this might be to increase the prestige of the university, and in the second case it might be
to appeal to readers who have a limited understanding of science.

An online "influencer" who sells you a new diet is not a reliable source of information either
(*does their advertising revenue depend on people buying products related to that diet?
are they attractive because of the diet or were they attractive before the diet also?
do we know for sure that they even follow the diet?
is their medical information about their health since pursuing the diet?*).

When you are looking for information you need to think *critically* about the sources.
Not every **scientific paper** is perfect, but the process by which they are published is incredibly demanding:

1. Development of testable question
2. Acquiring funding from someone who thinks the question is worthwile
3. Performing several months of rigorous experiments to answer the question
4. Writing a detailed account of the study in such detail that it can be repeated by others
5. Convincing at least two anonymous scientists that your work is trustworthy, reliable and interesting
6. Improving the paper by responding to criticisms from the editor and the anonymous reviewers
7. Publishing the paper and hoping it has impact, meaning that other scientists reference it and use its ideas

In comparison, here's the steps to publishing **a blog** (even by a PhD scientist!):

1. Write the blog
2. Click publish

**Know the difference.**

:::

Note that science ≠ technology.
Scientific knowledge may be applied in the design of technology.
Correct scientific knowledge can be applied to create a dangerous technology (e.g., the nuclear bomb).
This does not mean that the original scientific knowledge was flawed or dangerous (in and of itself).
Technology may be motivated by different reasons and principles than a purely scientific pursuit (e.g., profit).
We will discuss these topics in greater detail in semester 2.

## Models, Analysis and Synthesis

It is important to distinguish between ontological claims and epistemological claims.

The claim "humans are machines" may be interpreted as ontological, in that it suggests that people literally *are* machines in reality.
However, saying that "humans can be thought of as machines" is epistemological, and only means that the machine is a useful model for explaining how humans work.
Consider the video below, which is based on a famous depiction (1926) of the human body by a German scientific illustrator named Fritz Kahn.
In it, the body is depicted as a factory with miniature people manning the operations.
Clearly, it would be ridiculous to believe (ontologically) that this was what bodies were actually like.
Yet this familiar and simplistic model can serve a useful explanatory role.
Kahn lived at a time of industrialisation, so the factory was a feature of the popular consciousness.
He used the factory as an analogy to explain the workings of the body to a popular audience.

<iframe title="vimeo-player" src="https://player.vimeo.com/video/6505158?h=c6a9893476" width="640" height="360" frameborder="0" allowfullscreen></iframe>

[The human-as-factory model is still alive and well in some food science papers](https://ift.onlinelibrary.wiley.com/doi/epdf/10.1111/1750-3841.13216).
Such a model can be valuable as it simplifies complex systems and improves our ability to study them.
For example, it is difficult (ethically and practically) to do scientific studies with real people;
they may become sick and their lifestyles might influence the results.
For this reason it is difficult to study human digestion.
By modelling human digestion as a factory process, we can design miniature factories in laboratories where
digestion can be studied in a controlled manner, without potentially harming people.
However, we must be careful not to fall into the trap of assuming that people *are* machines (e.g., that they "only need fuel" and that they should "maximise their efficiency").

Scientists are frequently criticised as being "reductionists" by people who claim to be "holists".
However, most good scientists need to consider the whole as well as the parts.
Indeed, they need to consider how the parts interact in the formation of the whole.
This is what scientists usually mean by the "structure" of the systems they study.
Consider the video above again — the human body is not depicted as a collection of parts operating independently; instead,
the various sub-systems (gastrointestinal, respiratory, circulatory, etc.) work together in the (whole) system of the human body.
This moving between parts and wholes in the study of systems is characteristic of good science.

## The Sciences of Food

Food is studied by a variety of disciplines inside, outside and adjacent to food science.
There are food scientists, but also food geographers and food historians.
Even within the sciences there are a variety of disciplines, including:

- Food science
- Nutritional science
- Molecular gastronomy
- Gastrophysics

It is difficult to make a total separation between these disciplines.
Food scientists study nutritional science during their degrees.
Some go on to work with products that have primarily a nutritional function (e.g., infant formula).
Nutritional scientists study food science during their degrees.
Some go on to work in technical roles that are commonly occupied by food scientists (e.g., quality control).
The difference is really a matter of emphasis: food scientists devote more of their time on the systematic study of food processing, food structure and food chemistry, and have a broad conception of "food function" that encompasses nutrition but also other factors (e.g., convenience, taste, texture).
Nutritional scientists place a greater emphasis on the systematic study of the body and the manner in which nutrients are processed physiologically, as well as the population-wide trends in the consumption of specific nutrients and how this might be linked with health conditions.
These two types of scientist have significant overlaps in their knowledge but must specialise in some different topics to support their research.
Food scientists, for example, must understand the link between processing and nutritional quality of food, so they study more physics and engineering.
Nutritional scientists, for example, have to study large datasets about populations, so they study more statistics, and a selection of them go on to further study to work as dieticians, so they also learn about clinical topics.
Often they must work together (in universities or in companies) in order to fill in the gaps in their knowledge and a work effectively as a team.

::: {.callout-note}

## Food Scientists and Nutritional Scientists at UCC

Scientists at UCC have in recent years been working on a sports nutrition product (full disclosure: I am involved in the project).
The product is designed to enhance muscle recovery in high-performance athletes.

This project requires close collaboration between food scientists and nutritional scientists.
At the outset, nutritional scientists know what they want:

> to improve muscle recovery

but not how to achieve it, so food scientists develop the product concept further and the establish how it will be made.
During this stage the food scientists must design the product with the nutritional goal in mind while also ensuring it does not cause other issues (sensory, safety).

Once the product is manufactured the nutritional scientists determine whether the product works by performing a Clinical Trial.
Then it can be concluded whether it can be said with statistical confidence that the product enhances muscle recovery.

Finally, the food scientist and nutritional scientists will publish their results as a scientific paper.

:::

Occasionally, scientists consider an existing discipline to have ignored or downplayed an important topic, which they suggest warrants the creation of a new discipline.
This was the case with molecular gastronomy, created by the scientists Nicholas Kurti and Herve This, who felt that food science has paid insufficient attention to cooking.
Molecular gastronomy is sometimes considered a sub-discipline of food science and shares many of its methods and principles.
The more recently developed gastrophysics was proposed by the psychologist Charles Spence, and has highlighted how food experiences are influenced by psychological factors and the context of the experience.
Gastrophysics is closely related to sensory science, a long-standing sub-discipline of food science but which has less emphasis on psychological concepts.
Many of these disciplines are "sub-disciplines" insofar as they study a sub-set of problems within food science.
In set-theoretic language, food science is then the "power set" (the set of all those sub-sets).

Food scientists absorb these new directions and it comes to influence their work.
For example, when McClements tries to define what food science is for a popular audience he frequently appeals to research in molecular gastronomy.
As students, even though you do not have a dedicated university module in molecular gastronomy, there is nothing stopping you from reading and learning about molecular gastronomy.
Doing this might make you a better food scientist.

One of the goals of molecular gastronomy is to make cooking a more scientific process.
To achieve this one of its methods of investigation was to study recipes and attempt to explain scientifically steps in the recipe that were imprecise or vague.
Herve This, one of its co-founders, even proposed a kind of language that can be used as a tool to automate the generation of recipes.
We will discuss this language in the next lecture on food structure.

## References

Bornhorst, G. M., Gouseti, O., Wickham, M. S. J., & Bakalis, S. Engineering digestion: Multiscale Process of Food Digestion. *Journal of Food Science*, 81, R534-R543.

Burke, R., This, H., & Kelly, A. (2016). Molecular Gastronomy, in *Reference Module in Food Sciences*. [Available online](https://arrow.tudublin.ie/cgi/viewcontent.cgi?article=1196&context=tfschafart).

McClements, D. J. (2015). Future Foods: How Modern Science is Transforming the Way We Eat. Cham, Switzerland: Springer.
